# Generated by Django 4.1.6 on 2023-08-31 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gatepassHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngatepass', models.CharField(blank=True, max_length=64, null=True)),
                ('nama_tamu', models.CharField(blank=True, max_length=128, null=True)),
                ('nomor_identitas', models.CharField(blank=True, max_length=64, null=True)),
                ('nomor_kendaraan', models.CharField(blank=True, max_length=64, null=True)),
                ('jenis_kendaraan', models.CharField(blank=True, max_length=64, null=True)),
                ('tipe', models.CharField(blank=True, max_length=64, null=True)),
                ('tanggal_masuk', models.DateTimeField(blank=True, null=True, verbose_name='tanggal_masuk')),
                ('tanggal_keluar', models.DateTimeField(blank=True, null=True, verbose_name='tanggal_keluar')),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='gatepassPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(blank=True, max_length=64, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('gatepassH', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatepass_app.gatepassheader')),
            ],
        ),
        migrations.CreateModel(
            name='gatepassPermision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gatepassheader',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatepass_app.gatepasspermision'),
        ),
        migrations.CreateModel(
            name='gatepassDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(blank=True, max_length=128, null=True)),
                ('bertemu_dengan', models.CharField(blank=True, max_length=64, null=True)),
                ('department', models.CharField(blank=True, max_length=64, null=True)),
                ('tujuanH', models.CharField(blank=True, max_length=128, null=True)),
                ('tujuanD', models.CharField(blank=True, max_length=256, null=True)),
                ('no_surat_jalan', models.CharField(blank=True, max_length=64, null=True)),
                ('tujuan_pengiriman', models.CharField(blank=True, max_length=128, null=True)),
                ('tipe_gudang', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('gatepassH', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatepass_app.gatepassheader')),
            ],
        ),
    ]
