# Generated by Django 4.1.6 on 2024-11-07 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_category',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_location',
            },
        ),
        migrations.CreateModel(
            name='Machineelectrical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_machine_electrical',
            },
        ),
        migrations.CreateModel(
            name='Machinemechanical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_machine_mechanical',
            },
        ),
        migrations.CreateModel(
            name='Machineutility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_machine_utility',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dailyactivity_app_shift',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_status',
            },
        ),
        migrations.CreateModel(
            name='UtilityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('masalah', models.TextField()),
                ('penyebab', models.TextField()),
                ('tindakan', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='utility_images/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.location')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.machineutility')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.shift')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dailyactivity_app_utility_data',
            },
        ),
        migrations.CreateModel(
            name='MechanicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('masalah', models.TextField()),
                ('penyebab', models.TextField()),
                ('tindakan', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='mechanical_images/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.location')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.machinemechanical')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.shift')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dailyactivity_app_mechanical_data',
            },
        ),
        migrations.CreateModel(
            name='ElectricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('masalah', models.TextField()),
                ('penyebab', models.TextField()),
                ('tindakan', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='electrical_images/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.location')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.machineelectrical')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.shift')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dailyactivity_app_electrical_data',
            },
        ),
    ]
