# Generated by Django 4.1.6 on 2024-11-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemechanical',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.location'),
        ),
    ]
