# Generated by Django 4.1.6 on 2024-11-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0002_machinemechanical_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemechanical',
            name='location',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.location'),
        ),
    ]
