# Generated by Django 4.1.6 on 2024-11-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0003_alter_machinemechanical_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricaldata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.category'),
        ),
        migrations.AlterField(
            model_name='electricaldata',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status'),
        ),
        migrations.AlterField(
            model_name='machinemechanical',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.location'),
        ),
        migrations.AlterField(
            model_name='mechanicaldata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.category'),
        ),
        migrations.AlterField(
            model_name='mechanicaldata',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status'),
        ),
        migrations.AlterField(
            model_name='utilitydata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.category'),
        ),
        migrations.AlterField(
            model_name='utilitydata',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status'),
        ),
    ]
