# Generated by Django 4.1.6 on 2024-11-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0004_alter_electricaldata_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineelectrical',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.location'),
        ),
        migrations.AddField(
            model_name='machineelectrical',
            name='nomor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machinemechanical',
            name='nomor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machineutility',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.location'),
        ),
        migrations.AddField(
            model_name='machineutility',
            name='nomor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machinemechanical',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.location'),
        ),
    ]
