# Generated by Django 4.1.6 on 2024-11-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0005_machineelectrical_location_machineelectrical_nomor_and_more'),
    ]

    operations = [
        # Tidak ada operasi untuk mengubah id
    ]
