# Generated by Django 4.1.6 on 2024-11-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0007_alter_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineelectrical',
            name='location',
        ),
        migrations.RemoveField(
            model_name='machineelectrical',
            name='nomor',
        ),
        migrations.RemoveField(
            model_name='machinemechanical',
            name='location',
        ),
        migrations.RemoveField(
            model_name='machinemechanical',
            name='nomor',
        ),
        migrations.RemoveField(
            model_name='machineutility',
            name='location',
        ),
        migrations.RemoveField(
            model_name='machineutility',
            name='nomor',
        ),
        migrations.AlterField(
            model_name='electricaldata',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.category'),
        ),
        migrations.AlterField(
            model_name='electricaldata',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status'),
        ),
        migrations.AlterField(
            model_name='mechanicaldata',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.category'),
        ),
        migrations.AlterField(
            model_name='mechanicaldata',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status'),
        ),
        migrations.AlterField(
            model_name='utilitydata',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.category'),
        ),
        migrations.AlterField(
            model_name='utilitydata',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status'),
        ),
    ]
