# Generated by Django 4.1.6 on 2024-11-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0008_remove_machineelectrical_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemechanical',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.location'),
        ),
        migrations.AddField(
            model_name='machinemechanical',
            name='nomor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
