# Generated by Django 4.1.6 on 2024-11-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0009_machinemechanical_location_machinemechanical_nomor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machinemechanical',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.location'),
        ),
    ]
