# Generated by Django 4.1.6 on 2024-11-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0010_alter_location_id_alter_machinemechanical_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PICMechanical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nokar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_pic_mechanical',
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mechanicaldata',
            name='pic',
            field=models.ManyToManyField(blank=True, to='dailyactivity_app.picmechanical'),
        ),
    ]
