# Generated by Django 4.1.6 on 2024-11-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0011_picmechanical_alter_location_id_mechanicaldata_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicaldata',
            name='nomor_wo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mechanicaldata',
            name='waktu_pengerjaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
