# Generated by Django 4.1.6 on 2024-11-11 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0012_mechanicaldata_nomor_wo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicaldata',
            name='jam',
        ),
        migrations.AddField(
            model_name='mechanicaldata',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MechanicalDataPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanical_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.mechanicaldata')),
                ('pic_mechanical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.picmechanical')),
            ],
            options={
                'db_table': 'dailyactivity_app_mechanical_data_pic',
            },
        ),
        migrations.AlterField(
            model_name='mechanicaldata',
            name='pic',
            field=models.ManyToManyField(blank=True, through='dailyactivity_app.MechanicalDataPIC', to='dailyactivity_app.picmechanical'),
        ),
    ]
