# Generated by Django 4.1.6 on 2024-11-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0013_remove_mechanicaldata_jam_mechanicaldata_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanicaldata',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
