# Generated by Django 4.1.6 on 2024-11-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0014_rename_datetime_mechanicaldata_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicaldata',
            name='created_at',
        ),
        migrations.AddField(
            model_name='mechanicaldata',
            name='jam',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
