# Generated by Django 4.1.6 on 2024-11-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0015_remove_mechanicaldata_created_at_mechanicaldata_jam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicaldata',
            name='jam',
            field=models.TimeField(blank=True, default='08:00:00', null=True),
        ),
    ]
