# Generated by Django 4.1.6 on 2024-11-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0016_alter_mechanicaldata_jam'),
    ]

    operations = [
        migrations.CreateModel(
            name='PICElectrical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nokar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_pic_electrical',
            },
        ),
        migrations.AddField(
            model_name='electricaldata',
            name='nomor_wo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electricaldata',
            name='waktu_pengerjaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ElectricalDataPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrical_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.electricaldata')),
                ('pic_electrical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.picelectrical')),
            ],
            options={
                'db_table': 'dailyactivity_app_electrical_data_pic',
            },
        ),
        migrations.AddField(
            model_name='electricaldata',
            name='pic',
            field=models.ManyToManyField(blank=True, through='dailyactivity_app.ElectricalDataPIC', to='dailyactivity_app.picelectrical'),
        ),
    ]
