# Generated by Django 4.1.6 on 2024-11-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0019_machineutility_location_machineutility_nomor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PICUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nokar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_pic_utility',
            },
        ),
        migrations.AddField(
            model_name='utilitydata',
            name='nomor_wo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilitydata',
            name='waktu_pengerjaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UtilityDataPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.picutility')),
                ('utility_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.utilitydata')),
            ],
            options={
                'db_table': 'dailyactivity_app_utility_data_pic',
            },
        ),
        migrations.AddField(
            model_name='utilitydata',
            name='pic',
            field=models.ManyToManyField(blank=True, through='dailyactivity_app.UtilityDataPIC', to='dailyactivity_app.picutility'),
        ),
    ]
