# Generated by Django 4.1.6 on 2024-12-20 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailyactivity_app', '0020_picutility_utilitydata_nomor_wo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(max_length=11, null=True)),
                ('tgl_his', models.DateTimeField(null=True)),
                ('jam_his', models.CharField(max_length=12, null=True)),
                ('id_line', models.FloatField(null=True)),
                ('id_mesin', models.FloatField(null=True)),
                ('nomer', models.CharField(max_length=10, null=True)),
                ('id_section', models.FloatField(null=True)),
                ('id_pekerjaan', models.FloatField(null=True)),
                ('number_wo', models.CharField(max_length=15, null=True)),
                ('deskripsi_perbaikan', models.TextField(null=True)),
                ('id_penyebab', models.FloatField(null=True)),
                ('penyebab', models.TextField(null=True)),
                ('akar_masalah', models.TextField(null=True)),
                ('tindakan_perbaikan', models.TextField(null=True)),
                ('tindakan_pencegahan', models.TextField(null=True)),
                ('status_pekerjaan', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'dbo.tabel_main',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.DateTimeField(blank=True, null=True)),
                ('masalah', models.TextField()),
                ('penyebab', models.TextField(blank=True, null=True)),
                ('line', models.CharField(blank=True, max_length=255, null=True)),
                ('mesin', models.CharField(blank=True, max_length=255, null=True)),
                ('nomer', models.CharField(blank=True, max_length=50, null=True)),
                ('pekerjaan', models.TextField(blank=True, null=True)),
                ('status_pekerjaan', models.CharField(blank=True, max_length=100, null=True)),
                ('tindakan_perbaikan', models.TextField(blank=True, null=True)),
                ('tindakan_pencegahan', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='it_images/')),
                ('nomor_wo', models.CharField(blank=True, max_length=100, null=True)),
                ('waktu_pengerjaan', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dailyactivity_app_it_data',
            },
        ),
        migrations.CreateModel(
            name='LaporanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('masalah', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='laporan_images/')),
            ],
            options={
                'db_table': 'dailyactivity_app_laporan_data',
            },
        ),
        migrations.CreateModel(
            name='LaporanMechanicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('masalah', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='laporan_images/')),
            ],
            options={
                'db_table': 'dailyactivity_app_laporanmechanical_data',
            },
        ),
        migrations.CreateModel(
            name='LemburMechanicalDataPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laporanmechanical_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.laporanmechanicaldata')),
            ],
            options={
                'db_table': 'dailyactivity_app_lemburmechanical_data_pic',
            },
        ),
        migrations.CreateModel(
            name='MechanicalData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.DateTimeField(blank=True, null=True)),
                ('masalah', models.TextField()),
                ('penyebab', models.TextField(blank=True, null=True)),
                ('line', models.CharField(blank=True, max_length=255, null=True)),
                ('mesin', models.CharField(blank=True, max_length=255, null=True)),
                ('nomer', models.CharField(blank=True, max_length=50, null=True)),
                ('pekerjaan', models.TextField(blank=True, null=True)),
                ('status_pekerjaan', models.CharField(blank=True, max_length=100, null=True)),
                ('tindakan_perbaikan', models.TextField(blank=True, null=True)),
                ('tindakan_pencegahan', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mechanical_images/')),
                ('nomor_wo', models.CharField(blank=True, max_length=100, null=True)),
                ('waktu_pengerjaan', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dailyactivity_app_mechanical_data2',
            },
        ),
        migrations.CreateModel(
            name='PICIt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nokar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_pic_it',
            },
        ),
        migrations.CreateModel(
            name='PICLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nokar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_pic_laporan',
            },
        ),
        migrations.CreateModel(
            name='PICLaporanMechanical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nokar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_pic_laporanmechanical',
            },
        ),
        migrations.CreateModel(
            name='PICLembur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nokar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_pic_lembur',
            },
        ),
        migrations.CreateModel(
            name='PICLemburMechanical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nokar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_pic_lemburmechanical',
            },
        ),
        migrations.CreateModel(
            name='PICMechanical2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nokar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_pic_mechanical2',
            },
        ),
        migrations.CreateModel(
            name='PICUtility2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nokar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dailyactivity_app_pic_utility2',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('pic_project', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dailyactivity_app_projects',
            },
        ),
        migrations.CreateModel(
            name='UtilityData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.DateTimeField(blank=True, null=True)),
                ('masalah', models.TextField()),
                ('penyebab', models.TextField(blank=True, null=True)),
                ('line', models.CharField(blank=True, max_length=255, null=True)),
                ('mesin', models.CharField(blank=True, max_length=255, null=True)),
                ('nomer', models.CharField(blank=True, max_length=50, null=True)),
                ('pekerjaan', models.TextField(blank=True, null=True)),
                ('status_pekerjaan', models.CharField(blank=True, max_length=100, null=True)),
                ('tindakan_perbaikan', models.TextField(blank=True, null=True)),
                ('tindakan_pencegahan', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='utility_images/')),
                ('nomor_wo', models.CharField(blank=True, max_length=100, null=True)),
                ('waktu_pengerjaan', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dailyactivity_app_utility_data2',
            },
        ),
        migrations.AlterField(
            model_name='electricaldata',
            name='jam',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mechanicaldata',
            name='jam',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UtilityDataPIC2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.picutility2')),
                ('utility_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.utilitydata2')),
            ],
            options={
                'db_table': 'dailyactivity_app_utility_data_pic2',
            },
        ),
        migrations.AddField(
            model_name='utilitydata2',
            name='pic',
            field=models.ManyToManyField(blank=True, through='dailyactivity_app.UtilityDataPIC2', to='dailyactivity_app.picutility2'),
        ),
        migrations.AddField(
            model_name='utilitydata2',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.shift'),
        ),
        migrations.AddField(
            model_name='utilitydata2',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status'),
        ),
        migrations.AddField(
            model_name='utilitydata2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ScheduleMechanicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField(blank=True, null=True)),
                ('pekerjaan', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='laporan_images/')),
                ('pic_lemburmechanical', models.ManyToManyField(related_name='schedule_mechanical_data', through='dailyactivity_app.LemburMechanicalDataPIC', to='dailyactivity_app.piclemburmechanical')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dailyactivity_app_schedulemechanical_data',
            },
        ),
        migrations.CreateModel(
            name='ProjectIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('pic', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dailyactivity_app.project')),
            ],
            options={
                'db_table': 'dailyactivity_app_project_issues',
            },
        ),
        migrations.CreateModel(
            name='MechanicalDataPIC2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanical_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.mechanicaldata2')),
                ('pic_mechanical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.picmechanical2')),
            ],
            options={
                'db_table': 'dailyactivity_app_mechanical_data_pic2',
            },
        ),
        migrations.AddField(
            model_name='mechanicaldata2',
            name='pic',
            field=models.ManyToManyField(blank=True, through='dailyactivity_app.MechanicalDataPIC2', to='dailyactivity_app.picmechanical2'),
        ),
        migrations.AddField(
            model_name='mechanicaldata2',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.shift'),
        ),
        migrations.AddField(
            model_name='mechanicaldata2',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status'),
        ),
        migrations.AddField(
            model_name='mechanicaldata2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lemburmechanicaldatapic',
            name='pic_lemburmechanical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.piclemburmechanical'),
        ),
        migrations.AddField(
            model_name='lemburmechanicaldatapic',
            name='schedule_mechanical_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.schedulemechanicaldata'),
        ),
        migrations.CreateModel(
            name='LemburDataPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laporan_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.laporandata')),
                ('pic_lembur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.piclembur')),
            ],
            options={
                'db_table': 'dailyactivity_app_lembur_data_pic',
            },
        ),
        migrations.CreateModel(
            name='LaporanMechanicalDataPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laporanmechanical_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.laporanmechanicaldata')),
                ('pic_laporanmechanical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.piclaporanmechanical')),
            ],
            options={
                'db_table': 'dailyactivity_app_laporanmechanical_data_pic',
            },
        ),
        migrations.AddField(
            model_name='laporanmechanicaldata',
            name='pic',
            field=models.ManyToManyField(blank=True, through='dailyactivity_app.LaporanMechanicalDataPIC', to='dailyactivity_app.piclaporanmechanical'),
        ),
        migrations.AddField(
            model_name='laporanmechanicaldata',
            name='piclembur',
            field=models.ManyToManyField(blank=True, through='dailyactivity_app.LemburMechanicalDataPIC', to='dailyactivity_app.piclemburmechanical'),
        ),
        migrations.AddField(
            model_name='laporanmechanicaldata',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.shift'),
        ),
        migrations.AddField(
            model_name='laporanmechanicaldata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LaporanDataPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laporan_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.laporandata')),
                ('pic_laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.piclaporan')),
            ],
            options={
                'db_table': 'dailyactivity_app_laporan_data_pic',
            },
        ),
        migrations.AddField(
            model_name='laporandata',
            name='pic',
            field=models.ManyToManyField(blank=True, through='dailyactivity_app.LaporanDataPIC', to='dailyactivity_app.piclaporan'),
        ),
        migrations.AddField(
            model_name='laporandata',
            name='piclembur',
            field=models.ManyToManyField(blank=True, through='dailyactivity_app.LemburDataPIC', to='dailyactivity_app.piclembur'),
        ),
        migrations.AddField(
            model_name='laporandata',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.shift'),
        ),
        migrations.AddField(
            model_name='laporandata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ItDataPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.itdata')),
                ('pic_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.picit')),
            ],
            options={
                'db_table': 'dailyactivity_app_utility_data_it',
            },
        ),
        migrations.AddField(
            model_name='itdata',
            name='pic',
            field=models.ManyToManyField(blank=True, through='dailyactivity_app.ItDataPIC', to='dailyactivity_app.picit'),
        ),
        migrations.AddField(
            model_name='itdata',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.shift'),
        ),
        migrations.AddField(
            model_name='itdata',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.status'),
        ),
        migrations.AddField(
            model_name='itdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
