# Generated by Django 4.1.6 on 2025-08-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0021_tabelmain_itdata_laporandata_laporanmechanicaldata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laporandata',
            options={'verbose_name': 'Laporan Data', 'verbose_name_plural': 'Laporan Data'},
        ),
        migrations.AddField(
            model_name='laporandata',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laporandata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laporandata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='laporandata',
            name='voice_note_catatan',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
        migrations.AddField(
            model_name='laporandata',
            name='voice_note_masalah',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
        migrations.AddField(
            model_name='laporanmechanicaldata',
            name='catatan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laporanmechanicaldata',
            name='lama_pekerjaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laporanmechanicaldata',
            name='pic_masalah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectissue',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '0%'), ('10', '10%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('60', '60%'), ('70', '70%'), ('80', '80%'), ('90', '90%'), ('100', '100%')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='LaporanUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masalah', models.TextField()),
                ('jenis_pekerjaan', models.CharField(max_length=200)),
                ('lama_pekerjaan', models.CharField(max_length=100)),
                ('pic_masalah', models.CharField(max_length=100)),
                ('laporan_utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_utility', to='dailyactivity_app.laporandata')),
            ],
            options={
                'db_table': 'dailyactivity_app_laporanutility',
            },
        ),
        migrations.CreateModel(
            name='LaporanPekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masalah', models.TextField()),
                ('jenis_pekerjaan', models.CharField(max_length=200)),
                ('lama_pekerjaan', models.CharField(max_length=100)),
                ('pic_masalah', models.CharField(max_length=100)),
                ('laporan_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_pekerjaan', to='dailyactivity_app.laporanmechanicaldata')),
            ],
            options={
                'db_table': 'dailyactivity_app_laporanpekerjaan',
            },
        ),
        migrations.CreateModel(
            name='DetailPekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('jenis_pekerjaan', models.CharField(max_length=200)),
                ('lama_pekerjaan', models.CharField(max_length=100)),
                ('pic_pekerjaan', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pekerjaan', to='dailyactivity_app.laporandata')),
            ],
            options={
                'verbose_name': 'Detail Pekerjaan',
                'verbose_name_plural': 'Detail Pekerjaan',
                'db_table': 'dailyactivity_app_detail_pekerjaan',
            },
        ),
    ]
