# Generated by Django 4.1.6 on 2025-08-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0022_alter_laporandata_options_laporandata_catatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporandata',
            name='jenis_pekerjaan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laporandata',
            name='lama_pekerjaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laporandata',
            name='pic_pekerjaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mechanicaldata',
            name='tindakan_pencegahan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanicaldata',
            name='tindakan_perbaikan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mechanicaldata',
            name='pic',
            field=models.ManyToManyField(blank=True, through='dailyactivity_app.MechanicalDataPIC', to='dailyactivity_app.picmechanical2'),
        ),
        migrations.AlterField(
            model_name='mechanicaldatapic',
            name='pic_mechanical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyactivity_app.picmechanical2'),
        ),
    ]
