# Generated by Django 4.1.6 on 2025-08-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyactivity_app', '0002_add_maintenance_fields'),
        ('dailyactivity_app', '0002_add_mechanical_fields'),
        ('dailyactivity_app', '0023_laporandata_jenis_pekerjaan_and_more'),
    ]

    operations = [
    ]
