# Generated by Django 4.1.6 on 2023-02-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0002_userprofileinfo_is_bod_userprofileinfo_is_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=64),
        ),
    ]
