# Generated by Django 4.1.6 on 2023-02-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0003_alter_section_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
