# Generated by Django 4.1.6 on 2023-02-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0004_alter_section_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='employee_number',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='position',
            field=models.CharField(default=False, max_length=128),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='section',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='section',
            field=models.ManyToManyField(default=False, to='master_app.section'),
        ),
    ]
