# Generated by Django 4.1.6 on 2023-02-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0005_remove_userprofileinfo_employee_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='section',
            field=models.ManyToManyField(blank=True, default=False, related_name='sections', to='master_app.section'),
        ),
    ]
