# Generated by Django 4.1.6 on 2023-02-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0006_alter_userprofileinfo_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='section',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='section',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='master_app.section'),
        ),
    ]
