# Generated by Django 4.1.6 on 2023-02-21 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_app', '0007_remove_userprofileinfo_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='master_app.department'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='division',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='master_app.division'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='employee_ext',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='is_bod',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='is_supervisor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='position',
            field=models.CharField(blank=True, default=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
