# Generated by Django 4.1.6 on 2023-04-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(default=False, max_length=128, unique=True),
        ),
    ]
