# Generated by Django 4.1.6 on 2023-05-16 07:28

from django.db import migrations, models
import master_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0012_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=master_app.models.GenderField(default='NB'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
