# Generated by Django 4.1.6 on 2023-05-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0013_userprofileinfo_gender_userprofileinfo_is_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='is_status',
            new_name='is_contract',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_permanent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
