# Generated by Django 4.1.6 on 2023-05-26 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0014_rename_is_status_userprofileinfo_is_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='tanggal_lahir',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Lahir'),
        ),
    ]
