# Generated by Django 4.1.6 on 2023-05-26 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import master_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_app', '0015_userprofileinfo_tanggal_lahir'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeluargaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', master_app.models.GenderField(default='NB')),
                ('tanggal_lahir', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Lahir')),
                ('hubungan', models.CharField(choices=[('Istri', 'Istri'), ('Anak', 'Anak')], default=False, max_length=25)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
