# Generated by Django 4.1.6 on 2023-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0017_alter_userkeluargainfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeluargainfo',
            name='nama_lengkap',
            field=models.CharField(blank=True, default=False, max_length=200, null=True),
        ),
    ]
