# Generated by Django 4.1.6 on 2023-06-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0018_userkeluargainfo_nama_lengkap'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_operate_computer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
