# Generated by Django 4.1.6 on 2023-06-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0020_district_provinsi_village_regency_district_regency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provinsi',
            new_name='Province',
        ),
    ]
