# Generated by Django 4.1.6 on 2023-06-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0021_rename_provinsi_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='provinsi_name',
            new_name='province_name',
        ),
    ]
