# Generated by Django 4.1.6 on 2023-06-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0022_rename_provinsi_name_province_province_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regency',
            old_name='provinsi',
            new_name='province',
        ),
    ]
