# Generated by Django 4.1.6 on 2023-06-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0023_rename_provinsi_regency_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='tempat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_app.regency'),
        ),
    ]
