# Generated by Django 4.1.6 on 2023-06-27 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_app', '0024_userprofileinfo_tempat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileKTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat_ktp', models.TextField(default=False)),
                ('is_surat_ktp', models.BooleanField(default=False)),
                ('rt_ktp', models.CharField(max_length=8)),
                ('rw_ktp', models.CharField(max_length=8)),
                ('is_same_ktp', models.BooleanField(default=False)),
                ('kecamatan_ktp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.district')),
                ('kelurahan_ktp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.village')),
                ('kota_ktp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.regency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='no_telepon',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='no_telepon2',
            field=models.PositiveIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='no_telp2_hubungan',
            field=models.CharField(blank=True, choices=[('SUAMI/ISTRI', 'Suami Atau Istri'), ('ORANGTUA', 'Orangtua'), ('ANAK', 'Anak'), ('SAUDARA', 'Saudara')], default=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='noktp',
            field=models.PositiveBigIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, choices=[('SMA/SEDERAJAT', 'Sma Atau Sederajat'), ('D-1', 'D1'), ('D-2', 'D2'), ('D-3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('LAINNYA', 'Lainnya')], default=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='pendidikan_terakhir_others',
            field=models.CharField(blank=True, default=False, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='UserProfileKTPNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat_now', models.TextField(default=False)),
                ('is_surat_now', models.BooleanField(default=False)),
                ('rt_now', models.CharField(max_length=8)),
                ('rw_now', models.CharField(max_length=8)),
                ('tempat_milik_now', models.CharField(blank=True, choices=[('SMA/SEDERAJAT', 'Milik Sendiri'), ('D-1', 'Ikut Orangtua'), ('D-2', 'Kontrak'), ('D-3', 'Kost'), ('LAINNYA', 'Lainnya')], default=False, max_length=25, null=True)),
                ('nama_pemilik', models.CharField(blank=True, default=False, max_length=128, null=True)),
                ('no_telp_pemilik', models.PositiveIntegerField(blank=True, default=False, null=True)),
                ('kecamatan_now', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.district')),
                ('kelurahan_now', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.village')),
                ('kota_now', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.regency')),
                ('userKTP', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='master_app.userprofilektp')),
            ],
        ),
    ]
