# Generated by Django 4.1.6 on 2023-06-27 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0025_userprofilektp_userprofileinfo_no_telepon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeluargaHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nokk', models.PositiveBigIntegerField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userkeluargainfo',
            name='noktp',
            field=models.PositiveBigIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userkeluargainfo',
            name='pekerjaan',
            field=models.CharField(blank=True, choices=[('PNS/BUMN', 'Pns Atau Bumn'), ('Karyawan Swasta', 'Karyawan Swasta'), ('IRT', 'Irt'), ('Wirausaha', 'Wirausaha'), ('LAINNYA', 'Lainnya')], default=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userkeluargainfo',
            name='pekerjaan_others',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userkeluargainfo',
            name='tempat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_app.regency'),
        ),
        migrations.CreateModel(
            name='UserAhliWaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('tanggal_lahir', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Lahir')),
                ('noktp', models.PositiveBigIntegerField(blank=True, default=False, null=True)),
                ('hubungan', models.CharField(blank=True, choices=[('SUAMI/ISTRI', 'Suami Atau Istri'), ('ORANGTUA', 'Orangtua'), ('ANAK', 'Anak'), ('SAUDARA', 'Saudara')], default=False, max_length=25, null=True)),
                ('tempat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_app.regency')),
            ],
        ),
        migrations.AddField(
            model_name='userkeluargainfo',
            name='keluarga',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_app.userkeluargaheader'),
        ),
    ]
