# Generated by Django 4.1.6 on 2023-07-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0026_userkeluargaheader_userkeluargainfo_noktp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='no_telepon',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='no_telepon2',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
