# Generated by Django 4.1.6 on 2023-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0027_alter_userprofileinfo_no_telepon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilektpnow',
            name='no_telp_pemilik',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
