# Generated by Django 4.1.6 on 2023-07-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0028_alter_userprofilektpnow_no_telp_pemilik'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilektp',
            name='provinsi_ktp',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='master_app.province'),
        ),
        migrations.AddField(
            model_name='userprofilektpnow',
            name='provinsi_now',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='master_app.province'),
        ),
    ]
