# Generated by Django 4.1.6 on 2023-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0029_userprofilektp_provinsi_ktp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilektp',
            name='rt_ktp',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofilektp',
            name='rw_ktp',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofilektpnow',
            name='rt_now',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofilektpnow',
            name='rw_now',
            field=models.IntegerField(max_length=8),
        ),
    ]
