# Generated by Django 4.1.6 on 2024-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceisa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceisaconf',
            old_name='NIDPerusahaan',
            new_name='NID_perusahaan',
        ),
        migrations.RenameField(
            model_name='ceisaconf',
            old_name='nomorAjuCount',
            new_name='base_url',
        ),
        migrations.RenameField(
            model_name='ceisaconf',
            old_name='namaPerusahaan',
            new_name='nama_perusahaan',
        ),
        migrations.AddField(
            model_name='ceisaconf',
            name='nomor_aju_count',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
