# Generated by Django 4.1.6 on 2023-04-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rir_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_type', models.CharField(choices=[('Incoming Eksternal', 'Incoming Eksternal'), ('Incoming Internal', 'Incoming Internal')], max_length=25, null=True)),
                ('category', models.CharField(choices=[('Fabrics', 'Fabrics'), ('Chemicals', 'Chemicals'), ('Polymer', 'Polymer'), ('Ropes', 'Ropes'), ('Chopped Fibers', 'Chopped Fibers'), ('Chloroprene Polymer', 'Chloroprene Polymer')], max_length=25, null=True)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('po_number', models.CharField(blank=True, max_length=200, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('incoming_date', models.CharField(blank=True, max_length=200, null=True)),
                ('expired_date', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_special_judgement', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='special_judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pass', models.BooleanField(blank=True, default=False, null=True)),
                ('is_return', models.BooleanField(blank=True, default=False, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('rir', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rir_header')),
            ],
        ),
        migrations.CreateModel(
            name='rirapprovalsupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_supervisor', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_supervisor', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checked_supervisor', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_supervisor', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('specialjudgement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rir_header')),
            ],
        ),
        migrations.CreateModel(
            name='rirapprovalmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checked_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_manager', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('rir_approval_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovalsupervisor')),
            ],
        ),
        migrations.CreateModel(
            name='rir_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coa_content_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('appearence_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('restricted_substance_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('environmental_issue_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('coa_content_checkedby', models.BooleanField(blank=True, default=False, null=True)),
                ('appearence_checkedby', models.BooleanField(blank=True, default=False, null=True)),
                ('restricted_substance_checkedby', models.BooleanField(blank=True, default=False, null=True)),
                ('environmental_issue_checkedby', models.BooleanField(blank=True, default=False, null=True)),
                ('coa_content_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('appearence_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('restricted_substance_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('environmental_issue_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rir_header')),
            ],
        ),
    ]
