# Generated by Django 4.1.6 on 2023-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rir_detail',
            name='sample_test_checkedby',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rir_detail',
            name='sample_test_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rir_detail',
            name='sample_test_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
