# Generated by Django 4.1.6 on 2023-04-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0002_rir_detail_sample_test_checkedby_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rir_detail',
            new_name='rirDetail',
        ),
        migrations.RenameModel(
            old_name='rir_header',
            new_name='rirHeader',
        ),
        migrations.RenameModel(
            old_name='special_judgement',
            new_name='specialJudgement',
        ),
    ]
