# Generated by Django 4.1.6 on 2023-04-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0003_rename_rir_detail_rirdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirheader',
            name='rir_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
