# Generated by Django 4.1.6 on 2023-04-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0004_rirheader_rir_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rirdetail',
            old_name='appearence_checkedby',
            new_name='appearence_checked_by',
        ),
        migrations.RenameField(
            model_name='rirdetail',
            old_name='coa_content_checkedby',
            new_name='coa_content_checked_by',
        ),
        migrations.RenameField(
            model_name='rirdetail',
            old_name='environmental_issue_checkedby',
            new_name='environmental_issue_checked_by',
        ),
        migrations.RenameField(
            model_name='rirdetail',
            old_name='restricted_substance_checkedby',
            new_name='restricted_substance_checked_by',
        ),
        migrations.RenameField(
            model_name='rirdetail',
            old_name='sample_test_checkedby',
            new_name='sample_test_checked_by',
        ),
    ]
