# Generated by Django 4.1.6 on 2023-04-05 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0005_rename_appearence_checkedby_rirdetail_appearence_checked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rirheader',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='rirheader',
            name='incoming_date',
        ),
        migrations.AddField(
            model_name='rirheader',
            name='expired_at',
            field=models.DateTimeField(auto_now=True, verbose_name='expired at'),
        ),
        migrations.AddField(
            model_name='rirheader',
            name='incoming_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='incoming at'),
            preserve_default=False,
        ),
    ]
