# Generated by Django 4.1.6 on 2023-04-06 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc_app', '0006_remove_rirheader_expired_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rirDetailAppearence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearence_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('appearence_checked_by', models.BooleanField(blank=True, default=False, null=True)),
                ('appearence_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('appearence_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailCoaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coa_content_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('coa_content_checked_by', models.BooleanField(blank=True, default=False, null=True)),
                ('coa_content_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('coa_content_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailEnvironmentalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_issue_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('environmental_issue_checked_by', models.BooleanField(blank=True, default=False, null=True)),
                ('environmental_issue_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('environmental_issue_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailRestrictedSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_substance_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('restricted_substance_checked_by', models.BooleanField(blank=True, default=False, null=True)),
                ('restricted_substance_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
                ('restricted_substance_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailSampleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_test_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('sample_test_checked_by', models.BooleanField(blank=True, default=False, null=True)),
                ('sample_test_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
                ('sample_test_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='rirDetail',
        ),
    ]
