# Generated by Django 4.1.6 on 2023-04-06 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc_app', '0007_rirdetailappearence_rirdetailcoacontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rirDetailAppearenceCheckedby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearence_checked_by', models.BooleanField(blank=True, default=False, null=True)),
                ('appearence_remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailAppearenceJudgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearence_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('appearence_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('appearence_user_judgement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailCoaContentCheckedby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coa_content_checked_by', models.BooleanField(blank=True, default=False, null=True)),
                ('coa_content_remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailCoaContentJudgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coa_content_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('coa_content_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('coa_content_user_judgement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailEnvironmentalIssueCheckedby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_issue_checked_by', models.BooleanField(blank=True, default=False, null=True)),
                ('environmental_issue_remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailEnvironmentalIssueJudgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_issue_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('environmental_issue_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('environmental_issue_user_judgement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailRestrictedSubstanceCheckedby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_substance_checked_by', models.BooleanField(blank=True, default=False, null=True)),
                ('restricted_substance_remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailRestrictedSubstanceJudgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_substance_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('restricted_substance_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
                ('restricted_substance_user_judgement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailSampleTestCheckedby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_test_checked_by', models.BooleanField(blank=True, default=False, null=True)),
                ('sample_test_remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rirDetailSampleTestJudgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_test_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('sample_test_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
                ('sample_test_user_judgement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rirdetailcoacontent',
            name='coa_content_user',
        ),
        migrations.RemoveField(
            model_name='rirdetailcoacontent',
            name='header',
        ),
        migrations.RemoveField(
            model_name='rirdetailenvironmentalissue',
            name='environmental_issue_user',
        ),
        migrations.RemoveField(
            model_name='rirdetailenvironmentalissue',
            name='header',
        ),
        migrations.RemoveField(
            model_name='rirdetailrestrictedsubstance',
            name='header',
        ),
        migrations.RemoveField(
            model_name='rirdetailrestrictedsubstance',
            name='restricted_substance_user',
        ),
        migrations.RemoveField(
            model_name='rirdetailsampletest',
            name='header',
        ),
        migrations.RemoveField(
            model_name='rirdetailsampletest',
            name='sample_test_user',
        ),
        migrations.RenameField(
            model_name='rirapprovalmanager',
            old_name='reject_reason_manager',
            new_name='return_reason_manager',
        ),
        migrations.RenameField(
            model_name='rirapprovalmanager',
            old_name='rir_approval_manager',
            new_name='rir_approval_supervisor',
        ),
        migrations.RenameField(
            model_name='rirapprovalsupervisor',
            old_name='reject_reason_supervisor',
            new_name='return_reason_supervisor',
        ),
        migrations.RemoveField(
            model_name='specialjudgement',
            name='remark',
        ),
        migrations.AddField(
            model_name='rirapprovalmanager',
            name='review_manager',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rirapprovalsupervisor',
            name='review_supervisor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='rirDetailAppearence',
        ),
        migrations.DeleteModel(
            name='rirDetailCoaContent',
        ),
        migrations.DeleteModel(
            name='rirDetailEnvironmentalIssue',
        ),
        migrations.DeleteModel(
            name='rirDetailRestrictedSubstance',
        ),
        migrations.DeleteModel(
            name='rirDetailSampleTest',
        ),
        migrations.AddField(
            model_name='rirdetailsampletestcheckedby',
            name='sample_test_judgement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirdetailsampletestjudgement'),
        ),
        migrations.AddField(
            model_name='rirdetailsampletestcheckedby',
            name='sample_test_user_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rirdetailrestrictedsubstancecheckedby',
            name='restricted_substance_judgement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirdetailrestrictedsubstancejudgement'),
        ),
        migrations.AddField(
            model_name='rirdetailrestrictedsubstancecheckedby',
            name='restricted_substance_user_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rirdetailenvironmentalissuecheckedby',
            name='environmental_issue_judgement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirdetailenvironmentalissuejudgement'),
        ),
        migrations.AddField(
            model_name='rirdetailenvironmentalissuecheckedby',
            name='environmental_issue_user_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rirdetailcoacontentcheckedby',
            name='coa_content_judgement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirdetailcoacontentjudgement'),
        ),
        migrations.AddField(
            model_name='rirdetailcoacontentcheckedby',
            name='coa_content_user_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rirdetailappearencecheckedby',
            name='appearence_judgement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirdetailappearencejudgement'),
        ),
        migrations.AddField(
            model_name='rirdetailappearencecheckedby',
            name='appearence_user_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
