# Generated by Django 4.1.6 on 2023-04-06 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc_app', '0008_rirdetailappearencecheckedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirheader',
            name='expired_at',
            field=models.DateTimeField(verbose_name='expired at'),
        ),
        migrations.AlterField(
            model_name='rirheader',
            name='incoming_at',
            field=models.DateTimeField(verbose_name='incoming at'),
        ),
        migrations.CreateModel(
            name='rirApprovalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checked_by', models.BooleanField(blank=True, default=False, null=True)),
                ('is_supervisor', models.BooleanField(blank=True, default=False, null=True)),
                ('is_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rirapprovalmanager',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
        migrations.AddField(
            model_name='rirapprovalsupervisor',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
    ]
