# Generated by Django 4.1.6 on 2023-04-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0009_alter_rirheader_expired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirheader',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
