# Generated by Django 4.1.6 on 2023-04-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0010_rirheader_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirheader',
            name='category',
            field=models.CharField(choices=[('Fabrics', 'Fabrics'), ('Chemicals', 'Chemicals'), ('Polymer', 'Polymer'), ('Ropes', 'Ropes'), ('Chopped Fibers', 'Chopped Fibers'), ('Chloroprene Polymer', 'Chloroprene Polymer')], max_length=25),
        ),
        migrations.AlterField(
            model_name='rirheader',
            name='incoming_type',
            field=models.CharField(choices=[('Incoming Eksternal', 'Incoming Eksternal'), ('Incoming Internal', 'Incoming Internal')], max_length=25),
        ),
        migrations.AlterField(
            model_name='rirheader',
            name='lot_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rirheader',
            name='material',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rirheader',
            name='po_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rirheader',
            name='quantity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rirheader',
            name='vendor',
            field=models.CharField(max_length=200),
        ),
    ]
