# Generated by Django 4.1.6 on 2023-04-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0011_alter_rirheader_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirdetailappearencecheckedby',
            name='appearence_user_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
        migrations.AlterField(
            model_name='rirdetailappearencejudgement',
            name='appearence_user_judgement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
        migrations.AlterField(
            model_name='rirdetailcoacontentcheckedby',
            name='coa_content_user_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
        migrations.AlterField(
            model_name='rirdetailcoacontentjudgement',
            name='coa_content_user_judgement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
        migrations.AlterField(
            model_name='rirdetailenvironmentalissuecheckedby',
            name='environmental_issue_user_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
        migrations.AlterField(
            model_name='rirdetailenvironmentalissuejudgement',
            name='environmental_issue_user_judgement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
        migrations.AlterField(
            model_name='rirdetailrestrictedsubstancecheckedby',
            name='restricted_substance_user_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
        migrations.AlterField(
            model_name='rirdetailrestrictedsubstancejudgement',
            name='restricted_substance_user_judgement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
        migrations.AlterField(
            model_name='rirdetailsampletestcheckedby',
            name='sample_test_user_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
        migrations.AlterField(
            model_name='rirdetailsampletestjudgement',
            name='sample_test_user_judgement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirapprovallist'),
        ),
    ]
