# Generated by Django 4.1.6 on 2023-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0012_alter_rirdetailappearencecheckedby_appearence_user_checked_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rirMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('classification', models.CharField(choices=[('Fabrics', 'Fabrics'), ('Chemicals', 'Chemicals'), ('Polymer', 'Polymer'), ('Ropes', 'Ropes'), ('Chopped Fibers', 'Chopped Fibers'), ('Chloroprene Polymer', 'Chloroprene Polymer'), ('Raw Cords', 'Raw Cords')], max_length=25)),
                ('condition', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rirheader',
            name='category',
            field=models.CharField(choices=[('Fabrics', 'Fabrics'), ('Chemicals', 'Chemicals'), ('Polymer', 'Polymer'), ('Ropes', 'Ropes'), ('Chopped Fibers', 'Chopped Fibers'), ('Chloroprene Polymer', 'Chloroprene Polymer'), ('Raw Cords', 'Raw Cords')], max_length=25),
        ),
    ]
