# Generated by Django 4.1.6 on 2023-04-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0013_rirmaterial_alter_rirheader_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirmaterial',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
