# Generated by Django 4.1.6 on 2023-04-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0014_rirmaterial_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rirmaterial',
            old_name='status',
            new_name='classification_status',
        ),
        migrations.AlterField(
            model_name='rirmaterial',
            name='classification',
            field=models.CharField(choices=[('Fabrics', 'Fabrics'), ('Chemicals', 'Chemicals'), ('Polymer', 'Polymer'), ('Ropes', 'Ropes'), ('Chopped Fibers', 'Chopped Fibers'), ('Chloroprene Polymer', 'Chloroprene Polymer'), ('Raw Cords', 'Raw Cords')], max_length=50),
        ),
    ]
