# Generated by Django 4.1.6 on 2023-04-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0016_rirdetailappearencecheckedby_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirheader',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirmaterial'),
        ),
    ]
