# Generated by Django 4.1.6 on 2023-04-17 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0017_alter_rirheader_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryTypeRIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coa_content', models.BooleanField(blank=True, default=False, null=True)),
                ('appearance', models.BooleanField(blank=True, default=False, null=True)),
                ('restricted_substance', models.BooleanField(blank=True, default=False, null=True)),
                ('environmental_issue', models.BooleanField(blank=True, default=False, null=True)),
                ('sample_test', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.AlterField(
            model_name='rirheader',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.categorytyperir'),
        ),
        migrations.AlterField(
            model_name='rirmaterial',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.categorytyperir'),
        ),
    ]
