# Generated by Django 4.1.6 on 2023-04-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0018_categorytyperir_alter_rirheader_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirheader',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.categorytyperir'),
        ),
        migrations.AlterField(
            model_name='rirheader',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirmaterial'),
        ),
        migrations.CreateModel(
            name='rirSampleTestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checkedby', models.BooleanField(blank=True, default=False, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='RIRSampleTestAttachment/')),
                ('rir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
            ],
        ),
        migrations.CreateModel(
            name='rirRestrictedSubstanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checkedby', models.BooleanField(blank=True, default=False, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='RIRRestrictedSubstanceAttachment/')),
                ('rir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
            ],
        ),
        migrations.CreateModel(
            name='rirEnvironmentalIssueAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checkedby', models.BooleanField(blank=True, default=False, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='RIREnvironmentalIssueAttachment/')),
                ('rir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
            ],
        ),
        migrations.CreateModel(
            name='rirCoaContentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checkedby', models.BooleanField(blank=True, default=False, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='RIRCoaContentAttachment/')),
                ('rir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
            ],
        ),
        migrations.CreateModel(
            name='rirAppearanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_judgement', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checkedby', models.BooleanField(blank=True, default=False, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='RIRAppearanceAttachment/')),
                ('rir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.rirheader')),
            ],
        ),
    ]
