# Generated by Django 4.1.6 on 2023-04-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0019_alter_rirheader_category_alter_rirheader_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirheader',
            name='incoming_at_external',
            field=models.DateTimeField(blank=True, null=True, verbose_name='incoming at External(optional)'),
        ),
    ]
