# Generated by Django 4.1.6 on 2023-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0020_rirheader_incoming_at_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirheader',
            name='incoming_at_external',
            field=models.DateTimeField(blank=True, null=True, verbose_name='incoming at external'),
        ),
    ]
