# Generated by Django 4.1.6 on 2023-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0021_alter_rirheader_incoming_at_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirdetailappearencecheckedby',
            name='is_special_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailappearencejudgement',
            name='is_special_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailcoacontentcheckedby',
            name='is_special_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailcoacontentjudgement',
            name='is_special_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailenvironmentalissuecheckedby',
            name='is_special_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailenvironmentalissuejudgement',
            name='is_special_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailrestrictedsubstancecheckedby',
            name='is_special_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailrestrictedsubstancejudgement',
            name='is_special_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailsampletestcheckedby',
            name='is_special_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailsampletestjudgement',
            name='is_special_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
