# Generated by Django 4.1.6 on 2023-04-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0022_rirdetailappearencecheckedby_is_special_judgement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirdetailappearencecheckedby',
            name='is_checkedby',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailappearencejudgement',
            name='is_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailcoacontentcheckedby',
            name='is_checkedby',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailcoacontentjudgement',
            name='is_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailenvironmentalissuecheckedby',
            name='is_checkedby',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailrestrictedsubstancecheckedby',
            name='is_checkedby',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailrestrictedsubstancejudgement',
            name='is_judgement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirdetailsampletestcheckedby',
            name='is_checkedby',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
