# Generated by Django 4.1.6 on 2023-04-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0023_rirdetailappearencecheckedby_is_checkedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirdetailappearencecheckedby',
            name='appearence_remark',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='rirdetailappearencejudgement',
            name='appearence_remark',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='rirdetailcoacontentcheckedby',
            name='coa_content_remark',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='rirdetailcoacontentjudgement',
            name='coa_content_remark',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='rirdetailenvironmentalissuecheckedby',
            name='environmental_issue_remark',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='rirdetailenvironmentalissuejudgement',
            name='environmental_issue_remark',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='rirdetailrestrictedsubstancecheckedby',
            name='restricted_substance_remark',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='rirdetailrestrictedsubstancejudgement',
            name='restricted_substance_remark',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='rirdetailsampletestcheckedby',
            name='sample_test_remark',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='rirdetailsampletestjudgement',
            name='sample_test_remark',
            field=models.TextField(default='-'),
        ),
    ]
