# Generated by Django 4.1.6 on 2023-04-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0024_alter_rirdetailappearencecheckedby_appearence_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirdetailappearencecheckedby',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailappearencejudgement',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailcoacontentcheckedby',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailcoacontentjudgement',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailenvironmentalissuecheckedby',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailenvironmentalissuejudgement',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailrestrictedsubstancecheckedby',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailrestrictedsubstancejudgement',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailsampletestcheckedby',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailsampletestjudgement',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirheader',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
    ]
