# Generated by Django 4.1.6 on 2023-04-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0026_alter_rirdetailappearencecheckedby_is_special_judgement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rirdetailappearencecheckedby',
            name='is_checkedby',
        ),
        migrations.RemoveField(
            model_name='rirdetailappearencejudgement',
            name='is_judgement',
        ),
        migrations.RemoveField(
            model_name='rirdetailcoacontentcheckedby',
            name='is_checkedby',
        ),
        migrations.RemoveField(
            model_name='rirdetailcoacontentjudgement',
            name='is_judgement',
        ),
        migrations.RemoveField(
            model_name='rirdetailenvironmentalissuecheckedby',
            name='is_checkedby',
        ),
        migrations.RemoveField(
            model_name='rirdetailrestrictedsubstancecheckedby',
            name='is_checkedby',
        ),
        migrations.RemoveField(
            model_name='rirdetailrestrictedsubstancejudgement',
            name='is_judgement',
        ),
        migrations.RemoveField(
            model_name='rirdetailsampletestcheckedby',
            name='is_checkedby',
        ),
    ]
