# Generated by Django 4.1.6 on 2023-05-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0027_remove_rirdetailappearencecheckedby_is_checkedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirheader',
            name='is_return',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rirheader',
            name='is_sa',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
