# Generated by Django 4.1.6 on 2023-05-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0028_rirheader_is_return_rirheader_is_sa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirapprovalsupervisor',
            name='specialjudgement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.specialjudgement'),
        ),
    ]
