# Generated by Django 4.1.6 on 2023-05-07 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0029_alter_rirapprovalsupervisor_specialjudgement'),
    ]

    operations = [
        migrations.CreateModel(
            name='rirApprovalSupervisorAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='RIRSupervisorAttachment/')),
                ('specialJudgement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.specialjudgement')),
            ],
        ),
        migrations.CreateModel(
            name='rirApprovalManagerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='RIRManagerAttachment/')),
                ('specialJudgement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_app.specialjudgement')),
            ],
        ),
    ]
