# Generated by Django 4.1.6 on 2023-05-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0030_rirapprovalsupervisorattachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rirapprovalmanager',
            old_name='is_approve_manager',
            new_name='is_pass_manager',
        ),
        migrations.RenameField(
            model_name='rirapprovalmanager',
            old_name='is_rejected_manager',
            new_name='is_return_manager',
        ),
        migrations.RenameField(
            model_name='rirapprovalsupervisor',
            old_name='is_approve_supervisor',
            new_name='is_pass_supervisor',
        ),
        migrations.RenameField(
            model_name='rirapprovalsupervisor',
            old_name='is_rejected_supervisor',
            new_name='is_return_supervisor',
        ),
    ]
