# Generated by Django 4.1.6 on 2023-05-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0031_rename_is_approve_manager_rirapprovalmanager_is_pass_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirapprovalmanager',
            name='is_pass_manager',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Pass'),
        ),
        migrations.AlterField(
            model_name='rirapprovalmanager',
            name='is_return_manager',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Return'),
        ),
    ]
