# Generated by Django 4.1.6 on 2023-05-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0032_alter_rirapprovalmanager_is_pass_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirheader',
            name='quantity_actual',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
