# Generated by Django 4.1.6 on 2023-05-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0033_rirheader_quantity_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirdetailappearencecheckedby',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailappearencejudgement',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailenvironmentalissuecheckedby',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailenvironmentalissuejudgement',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailrestrictedsubstancecheckedby',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailrestrictedsubstancejudgement',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailsampletestcheckedby',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rirdetailsampletestjudgement',
            name='is_special_judgement',
            field=models.BooleanField(default=False),
        ),
    ]
