# Generated by Django 4.1.6 on 2023-05-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0035_alter_rirdetailappearencecheckedby_is_special_judgement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rirapprovalmanager',
            old_name='return_reason_manager',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='rirapprovalsupervisor',
            old_name='return_reason_supervisor',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='rirapprovalmanager',
            name='review_manager',
        ),
        migrations.RemoveField(
            model_name='rirapprovalsupervisor',
            name='review_supervisor',
        ),
    ]
