# Generated by Django 4.1.6 on 2023-05-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0036_rename_return_reason_manager_rirapprovalmanager_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rirVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=200)),
                ('person_name', models.CharField(max_length=200)),
                ('vendor_code', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('term_of_payment', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
    ]
