# Generated by Django 4.1.6 on 2023-05-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0037_rirvendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rirvendor',
            old_name='classification',
            new_name='classification_vendor',
        ),
    ]
