# Generated by Django 4.1.6 on 2023-05-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0038_rename_classification_rirvendor_classification_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rirvendor',
            old_name='address',
            new_name='vendor_address',
        ),
        migrations.RenameField(
            model_name='rirvendor',
            old_name='classification_vendor',
            new_name='vendor_classification',
        ),
        migrations.RenameField(
            model_name='rirvendor',
            old_name='company',
            new_name='vendor_company',
        ),
        migrations.RenameField(
            model_name='rirvendor',
            old_name='created_at',
            new_name='vendor_created_at',
        ),
        migrations.RenameField(
            model_name='rirvendor',
            old_name='fax',
            new_name='vendor_fax',
        ),
        migrations.RenameField(
            model_name='rirvendor',
            old_name='person_name',
            new_name='vendor_person_name',
        ),
        migrations.RenameField(
            model_name='rirvendor',
            old_name='telephone',
            new_name='vendor_telephone',
        ),
        migrations.RenameField(
            model_name='rirvendor',
            old_name='term_of_payment',
            new_name='vendor_term_of_payment',
        ),
        migrations.RenameField(
            model_name='rirvendor',
            old_name='updated_at',
            new_name='vendor_updated_at',
        ),
        migrations.RenameField(
            model_name='rirvendor',
            old_name='vendor_code',
            new_name='vendor_vendor_code',
        ),
    ]
