# Generated by Django 4.1.6 on 2023-05-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0039_rename_address_rirvendor_vendor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirvendor',
            name='vendor_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rirvendor',
            name='vendor_classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rirvendor',
            name='vendor_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rirvendor',
            name='vendor_fax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rirvendor',
            name='vendor_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rirvendor',
            name='vendor_telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rirvendor',
            name='vendor_term_of_payment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rirvendor',
            name='vendor_vendor_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
