# Generated by Django 4.1.6 on 2023-05-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0040_alter_rirvendor_vendor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirvendor',
            name='vendor_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
