# Generated by Django 4.1.6 on 2023-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0041_rirvendor_vendor_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirvendor',
            name='vendor_classification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rirvendor',
            name='vendor_vendor_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
