# Generated by Django 4.1.6 on 2023-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0042_alter_rirvendor_vendor_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirheader',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
