# Generated by Django 4.1.6 on 2023-05-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0043_rirheader_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirheader',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
