# Generated by Django 4.1.6 on 2023-02-28 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', models.TextField(blank=True, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
                ('description_3', models.TextField(blank=True, null=True)),
                ('description_4', models.TextField(blank=True, null=True)),
                ('description_5', models.TextField(blank=True, null=True)),
                ('description_6', models.TextField(blank=True, null=True)),
                ('rp_detail_1', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rp_detail_2', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rp_detail_3', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rp_detail_4', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rp_detail_5', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rp_detail_6', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('attachment', models.FileField(upload_to='')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cashPaymentApprovalAccountingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_manager_accounting', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_manager_accounting', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_manager_accounting', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='cashPaymentApprovalPresident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_president', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_president', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_president', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('cashPayment_approval_accounting_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpaymentapprovalaccountingmanager')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cashPaymentApprovalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_manager', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('cashPayment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpayment')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cashPaymentApprovalCashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, max_length=128, null=True)),
                ('is_approve_cashier', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_cashier', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_cashier', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('cashPayment_approval_president', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpaymentapprovalpresident')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cashpaymentapprovalaccountingmanager',
            name='cashPayment_approval_manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpaymentapprovalmanager'),
        ),
        migrations.AddField(
            model_name='cashpaymentapprovalaccountingmanager',
            name='manager_accounting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
