# Generated by Django 4.1.6 on 2023-02-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='rp_total',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
