# Generated by Django 4.1.6 on 2023-03-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0002_cashpayment_rp_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashpayment',
            old_name='attachment',
            new_name='cashPayment_attachment',
        ),
    ]
