# Generated by Django 4.1.6 on 2023-03-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0003_rename_attachment_cashpayment_cashpayment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpayment',
            name='cashPayment_attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
