# Generated by Django 4.1.6 on 2023-03-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0004_alter_cashpayment_cashpayment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='description_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_10',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_11',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_12',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_7',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_8',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_9',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashpayment',
            name='cashPayment_attachment',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
    ]
