# Generated by Django 4.1.6 on 2023-03-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0005_cashpayment_description_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashpayment',
            name='cashPayment_attachment',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_10',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_11',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_12',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_5',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_6',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_7',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_8',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='description_9',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_1',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_10',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_11',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_12',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_2',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_3',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_4',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_5',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_6',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_7',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_8',
        ),
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_detail_9',
        ),
        migrations.CreateModel(
            name='cashPaymentDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rp_detail', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cashPayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpayment')),
            ],
        ),
        migrations.CreateModel(
            name='cashPaymentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='cashPaymentAttachments/')),
                ('cashPayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpayment')),
            ],
        ),
    ]
