# Generated by Django 4.1.6 on 2023-03-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0006_remove_cashpayment_cashpayment_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashpayment',
            name='rp_total',
        ),
    ]
