# Generated by Django 4.1.6 on 2023-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0007_remove_cashpayment_rp_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='description_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_1',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_10',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_11',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_12',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_2',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_3',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_4',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_5',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_6',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_7',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_8',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='rp_detail_9',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='cashPaymentDescription',
        ),
    ]
