# Generated by Django 4.1.6 on 2023-03-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0008_cashpayment_description_1_cashpayment_description_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='rp_total',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
