# Generated by Django 4.1.6 on 2023-03-01 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0009_cashpayment_rp_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpaymentattachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='cashPaymentAttachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
