# Generated by Django 4.1.6 on 2023-03-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0010_alter_cashpaymentattachment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpaymentattachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='cashPaymentAttachments/'),
        ),
    ]
