# Generated by Django 4.1.6 on 2023-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0011_alter_cashpaymentattachment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpaymentapprovalaccountingmanager',
            name='is_checked_manager_accounting',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cashpaymentapprovalcashier',
            name='is_checked_cashier',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cashpaymentapprovalmanager',
            name='is_checked_manager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cashpaymentapprovalpresident',
            name='is_checked_president',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
