# Generated by Django 4.1.6 on 2023-03-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0012_cashpaymentapprovalaccountingmanager_is_checked_manager_accounting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashpaymentapprovalcashier',
            name='ticket_no',
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='is_credit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='is_debit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
