# Generated by Django 4.1.6 on 2023-03-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0013_remove_cashpaymentapprovalcashier_ticket_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_cashPayment', models.BigIntegerField(blank=True, null=True)),
                ('exchange_rate', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
