# Generated by Django 4.1.6 on 2023-03-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0014_masteraccounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='is_settle',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
