# Generated by Django 4.1.6 on 2023-03-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0015_cashpayment_is_settle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='settle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
