# Generated by Django 4.1.6 on 2023-03-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0016_cashpayment_settle'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashPaymentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_cashPayment_in', models.BigIntegerField(blank=True, null=True)),
                ('balance_cashPayment_out', models.BigIntegerField(blank=True, null=True)),
                ('exchange_rate', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cashPayment_balance_no', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
        migrations.DeleteModel(
            name='masterAccounting',
        ),
    ]
