# Generated by Django 4.1.6 on 2023-03-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0017_cashpaymentbalance_delete_masteraccounting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashpaymentbalance',
            old_name='balance_cashPayment_in',
            new_name='balance_cashPayment_close',
        ),
        migrations.RenameField(
            model_name='cashpaymentbalance',
            old_name='balance_cashPayment_out',
            new_name='balance_cashPayment_open',
        ),
        migrations.RenameField(
            model_name='cashpaymentbalance',
            old_name='exchange_rate',
            new_name='exchange_rate_close',
        ),
        migrations.AddField(
            model_name='cashpaymentbalance',
            name='exchange_rate_open',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
