# Generated by Django 4.1.6 on 2023-03-15 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0018_rename_balance_cashpayment_in_cashpaymentbalance_balance_cashpayment_close_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashierAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='cashierAttachments/')),
                ('cashPayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpayment')),
            ],
        ),
    ]
