# Generated by Django 4.1.6 on 2023-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0019_cashierattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='adv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='is_adv',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
