# Generated by Django 4.1.6 on 2023-03-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0020_cashpayment_adv_cashpayment_is_adv'),
    ]

    operations = [
        migrations.CreateModel(
            name='settleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='settleAttachments/')),
                ('cashPayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpayment')),
            ],
        ),
        migrations.CreateModel(
            name='advAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='advAttachments/')),
                ('cashPayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpayment')),
            ],
        ),
    ]
