# Generated by Django 4.1.6 on 2023-04-03 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting_app', '0021_settleattachment_advattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='advanceApprovalAccountingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_manager_accounting', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_manager_accounting', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checked_manager_accounting', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_manager_accounting', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='type',
            field=models.CharField(choices=[('Transfer Cash', 'Transfer Cash'), ('Transfer Bank', 'Transfer Bank')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='advanceApprovalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checked_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_manager', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('advance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpayment')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='advanceApprovalCashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_cashier', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checked_cashier', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('advance_approval_accounting_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.advanceapprovalaccountingmanager')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='advanceapprovalaccountingmanager',
            name='advance_approval_manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.advanceapprovalmanager'),
        ),
        migrations.AddField(
            model_name='advanceapprovalaccountingmanager',
            name='manager_accounting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
