# Generated by Django 4.1.6 on 2023-04-04 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting_app', '0022_advanceapprovalaccountingmanager_cashpayment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceapprovalcashier',
            name='advance_approval_accounting_manager',
        ),
        migrations.CreateModel(
            name='advanceApprovalPresident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_president', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_president', models.BooleanField(blank=True, default=False, null=True)),
                ('is_checked_president', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_president', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('advance_approval_accounting_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.advanceapprovalaccountingmanager')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='advanceapprovalcashier',
            name='president',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.advanceapprovalpresident'),
        ),
    ]
