# Generated by Django 4.1.6 on 2023-04-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0023_remove_advanceapprovalcashier_advance_approval_accounting_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advanceapprovalcashier',
            old_name='president',
            new_name='advance_approval_cashier',
        ),
    ]
