# Generated by Django 4.1.6 on 2023-04-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0024_rename_president_advanceapprovalcashier_advance_approval_cashier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advanceapprovalcashier',
            old_name='advance_approval_cashier',
            new_name='advance_approval_president',
        ),
    ]
