# Generated by Django 4.1.6 on 2023-06-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0025_rename_advance_approval_cashier_advanceapprovalcashier_advance_approval_president'),
    ]

    operations = [
        migrations.CreateModel(
            name='coaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(blank=True, max_length=126, null=True)),
                ('cost_centre', models.CharField(blank=True, max_length=126, null=True)),
                ('description', models.CharField(blank=True, max_length=126, null=True)),
                ('status', models.CharField(blank=True, max_length=126, null=True)),
                ('structure_code', models.CharField(blank=True, max_length=126, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='rel_cashPayment_coaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('cashPayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpayment')),
                ('coaCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.coacode')),
            ],
        ),
    ]
