# Generated by Django 4.1.6 on 2023-06-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0026_coacode_rel_cashpayment_coacode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode',
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_1_manual_roats', to='accounting_app.coacode'),
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_10_manual_roats', to='accounting_app.coacode'),
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_11_manual_roats', to='accounting_app.coacode'),
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_12_manual_roats', to='accounting_app.coacode'),
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_2_manual_roats', to='accounting_app.coacode'),
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_3_manual_roats', to='accounting_app.coacode'),
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_4_manual_roats', to='accounting_app.coacode'),
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_5_manual_roats', to='accounting_app.coacode'),
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_6_manual_roats', to='accounting_app.coacode'),
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_7_manual_roats', to='accounting_app.coacode'),
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_8_manual_roats', to='accounting_app.coacode'),
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_9_manual_roats', to='accounting_app.coacode'),
        ),
    ]
