# Generated by Django 4.1.6 on 2023-06-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0028_alter_rel_cashpayment_coacode_coacode_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_1',
        ),
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_10',
        ),
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_11',
        ),
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_12',
        ),
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_2',
        ),
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_3',
        ),
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_4',
        ),
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_5',
        ),
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_6',
        ),
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_7',
        ),
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_8',
        ),
        migrations.RemoveField(
            model_name='rel_cashpayment_coacode',
            name='coaCode_9',
        ),
        migrations.AddField(
            model_name='rel_cashpayment_coacode',
            name='coaCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.coacode'),
        ),
    ]
