# Generated by Django 4.1.6 on 2023-06-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0029_remove_rel_cashpayment_coacode_coacode_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rel_cashPayment_coaCode',
            new_name='rel_cashPayment_accountcode',
        ),
        migrations.RenameField(
            model_name='rel_cashpayment_accountcode',
            old_name='coaCode',
            new_name='account_code',
        ),
    ]
