# Generated by Django 4.1.6 on 2024-03-26 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting_app', '0030_rename_rel_cashpayment_coacode_rel_cashpayment_accountcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_debit', models.BooleanField(blank=True, default=False, null=True)),
                ('is_credit', models.BooleanField(blank=True, default=False, null=True)),
                ('is_settle', models.BooleanField(blank=True, default=False, null=True)),
                ('is_adv', models.BooleanField(blank=True, default=False, null=True)),
                ('adv', models.CharField(blank=True, max_length=200, null=True)),
                ('settle', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('Transfer Cash', 'Transfer Cash'), ('Transfer Bank', 'Transfer Bank')], max_length=25, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('ticket_no', models.CharField(blank=True, max_length=128, null=True)),
                ('rp_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_1', models.TextField(blank=True, null=True)),
                ('rp_detail_1', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
                ('rp_detail_2', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_3', models.TextField(blank=True, null=True)),
                ('rp_detail_3', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_4', models.TextField(blank=True, null=True)),
                ('rp_detail_4', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_5', models.TextField(blank=True, null=True)),
                ('rp_detail_5', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_6', models.TextField(blank=True, null=True)),
                ('rp_detail_6', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_7', models.TextField(blank=True, null=True)),
                ('rp_detail_7', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_8', models.TextField(blank=True, null=True)),
                ('rp_detail_8', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_9', models.TextField(blank=True, null=True)),
                ('rp_detail_9', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_10', models.TextField(blank=True, null=True)),
                ('rp_detail_10', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_11', models.TextField(blank=True, null=True)),
                ('rp_detail_11', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description_12', models.TextField(blank=True, null=True)),
                ('rp_detail_12', models.PositiveBigIntegerField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
