# Generated by Django 4.1.6 on 2024-03-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0031_cashreceived'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashReceivedBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_cashReceived_open', models.BigIntegerField(blank=True, null=True)),
                ('balance_cashReceived_close', models.BigIntegerField(blank=True, null=True)),
                ('exchange_rate_open', models.PositiveBigIntegerField(blank=True, null=True)),
                ('exchange_rate_close', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cashReceived_balance_no', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='rel_cashReceived_accountcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.coacode')),
                ('cashPayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpayment')),
            ],
        ),
        migrations.CreateModel(
            name='cashReceivedAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='cashPaymentAttachments/')),
                ('cashPayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.cashpayment')),
            ],
        ),
    ]
