# Generated by Django 4.1.6 on 2023-05-16 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import master_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalApprovalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_foreman', models.BooleanField(blank=True, default=False, null=True)),
                ('is_supervisor', models.BooleanField(blank=True, default=False, null=True)),
                ('is_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('is_hr', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='medicalHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='medicalDetailPasienKeluarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pasien', models.CharField(blank=True, max_length=128, null=True)),
                ('tanggal_lahir', models.DateTimeField(auto_now_add=True, null=True, verbose_name='tanggal lahir')),
                ('jenis_kelamin', master_app.models.GenderField(blank=True, null=True)),
                ('hubungan', models.CharField(choices=[('Istri', 'Istri'), ('Anak', 'Anak')], default=False, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalheader')),
            ],
        ),
        migrations.CreateModel(
            name='medicalDetailInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pelayanan', models.CharField(choices=[('Istri', 'Istri'), ('Anak', 'Anak')], default=False, max_length=25, null=True)),
                ('melahirkan', models.CharField(choices=[('Istri', 'Istri'), ('Anak', 'Anak')], default=False, max_length=25, null=True)),
                ('tanggal_berobat', models.DateTimeField(auto_now_add=True, null=True, verbose_name='tanggal berobat')),
                ('diagnosa', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalheader')),
            ],
        ),
        migrations.CreateModel(
            name='medicalDetailDokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokter', models.CharField(blank=True, max_length=128, null=True)),
                ('hubungan', models.CharField(choices=[('Rumah Sakit', 'Rumah Sakit'), ('klinik', 'Klinik'), ('Praktek Dokter', 'Praktek Dokter'), ('Bidan', 'Bidan')], max_length=25)),
                ('nama_klinik', models.CharField(blank=True, max_length=128, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalheader')),
            ],
        ),
        migrations.CreateModel(
            name='medicalClaimStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lengkap', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalheader')),
            ],
        ),
        migrations.CreateModel(
            name='medicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='MedicalAttachment/')),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalheader')),
            ],
        ),
        migrations.CreateModel(
            name='medicalApprovalSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalheader')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalapprovallist')),
            ],
        ),
        migrations.CreateModel(
            name='medicalApprovalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalapprovallist')),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalheader')),
            ],
        ),
        migrations.CreateModel(
            name='medicalApprovalHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalapprovallist')),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalheader')),
            ],
        ),
        migrations.CreateModel(
            name='medicalApprovalForeman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('foreman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalapprovallist')),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalheader')),
            ],
        ),
    ]
