# Generated by Django 4.1.6 on 2023-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalheader',
            name='is_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
