# Generated by Django 4.1.6 on 2023-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0002_medicalheader_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalapprovalforeman',
            name='is_approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicalapprovalforeman',
            name='is_reject',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicalapprovalhr',
            name='is_approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicalapprovalhr',
            name='is_reject',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicalapprovalmanager',
            name='is_approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicalapprovalmanager',
            name='is_reject',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicalapprovalsupervisor',
            name='is_approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicalapprovalsupervisor',
            name='is_reject',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
