# Generated by Django 4.1.6 on 2023-05-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0003_medicalapprovalforeman_is_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalheader',
            name='medical_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
