# Generated by Django 4.1.6 on 2023-05-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0004_medicalheader_medical_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldetaildokter',
            old_name='hubungan',
            new_name='tempat_pelayanan',
        ),
    ]
