# Generated by Django 4.1.6 on 2023-05-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0005_rename_hubungan_medicaldetaildokter_tempat_pelayanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalheader',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='medicalheader',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='medicalheader',
            name='is_foreman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalheader',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalheader',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
