# Generated by Django 4.1.6 on 2023-05-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0006_remove_medicalheader_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalclaimstatus',
            name='reason',
        ),
        migrations.AddField(
            model_name='medicalapprovalforeman',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalapprovalhr',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalapprovalmanager',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalapprovalsupervisor',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
