# Generated by Django 4.1.6 on 2023-05-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0007_remove_medicalclaimstatus_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetailinformation',
            name='tanggal_berobat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tanggal berobat'),
        ),
        migrations.AlterField(
            model_name='medicaldetailpasienkeluarga',
            name='tanggal_lahir',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tanggal lahir'),
        ),
    ]
