# Generated by Django 4.1.6 on 2023-05-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0008_alter_medicaldetailinformation_tanggal_berobat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetailpasienkeluarga',
            name='hubungan',
            field=models.CharField(blank=True, choices=[('Istri', 'Istri'), ('Anak', 'Anak')], default=False, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetailpasienkeluarga',
            name='tanggal_lahir',
            field=models.DateTimeField(verbose_name='tanggal lahir'),
        ),
    ]
