# Generated by Django 4.1.6 on 2023-05-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0009_alter_medicaldetailpasienkeluarga_hubungan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetaildokter',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicaldetaildokter',
            name='nama_dokter',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='medicaldetaildokter',
            name='nama_klinik',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='medicaldetaildokter',
            name='no_telp',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='medicaldetailinformation',
            name='diagnosa',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='medicaldetailinformation',
            name='jenis_pelayanan',
            field=models.CharField(choices=[('Rawat Jalan', 'Rawat Jalan'), ('Rawat Inap', 'Rawat Inap')], default=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='medicaldetailinformation',
            name='tanggal_berobat',
            field=models.DateTimeField(verbose_name='tanggal berobat'),
        ),
    ]
