# Generated by Django 4.1.6 on 2023-05-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0010_alter_medicaldetaildokter_alamat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetailinformation',
            name='melahirkan',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Caesar', 'Caesar'), ('Keguguran', 'Keguguran')], default=False, max_length=25, null=True),
        ),
    ]
