# Generated by Django 4.1.6 on 2023-05-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0011_alter_medicaldetailinformation_melahirkan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldetaildokter',
            old_name='nama_klinik',
            new_name='nama_tempat',
        ),
    ]
