# Generated by Django 4.1.6 on 2023-05-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0012_rename_nama_klinik_medicaldetaildokter_nama_tempat'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalheader',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicalheader',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
