# Generated by Django 4.1.6 on 2023-05-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0013_medicalheader_is_complete_medicalheader_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetailpasienkeluarga',
            name='tanggal_lahir',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tanggal lahir'),
        ),
    ]
