# Generated by Django 4.1.6 on 2023-05-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0014_alter_medicaldetailpasienkeluarga_tanggal_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalheader',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalheader',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
