# Generated by Django 4.1.6 on 2023-05-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0015_alter_medicalheader_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalheader',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
    ]
