# Generated by Django 4.1.6 on 2023-05-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0016_medicalheader_is_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalheader',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrd_app.medicalapprovallist'),
        ),
    ]
