# Generated by Django 4.1.6 on 2023-05-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0017_medicalheader_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalclaimstatus',
            name='tidak_lengkap',
            field=models.CharField(blank=True, choices=[('Klaim tidak lengkap', 'Klaim Tidak Lengkap'), ('Klaim ditolak', 'Klaim Ditolak')], default=False, max_length=25, null=True),
        ),
    ]
