# Generated by Django 4.1.6 on 2023-05-25 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0018_medicalclaimstatus_tidak_lengkap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldetailinformation',
            name='tanggal_berobat',
        ),
        migrations.AddField(
            model_name='medicaldetailinformation',
            name='tanggal_berobat_mulai',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='tanggal berobat mulai'),
        ),
        migrations.AddField(
            model_name='medicaldetailinformation',
            name='tanggal_berobat_selesai',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='tanggal berobat selesai'),
        ),
        migrations.AlterField(
            model_name='medicaldetailinformation',
            name='jenis_pelayanan',
            field=models.CharField(choices=[('Rawat Jalan', 'Rawat Jalan'), ('Rawat Inap', 'Rawat Inap'), ('Kacamata', 'Kacamata'), ('Persalinan', 'Persalinan')], default=False, max_length=25),
        ),
    ]
