# Generated by Django 4.1.6 on 2023-05-28 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0018_userkeluargainfo_nama_lengkap'),
        ('hrd_app', '0019_remove_medicaldetailinformation_tanggal_berobat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldetailpasienkeluarga',
            name='hubungan',
        ),
        migrations.RemoveField(
            model_name='medicaldetailpasienkeluarga',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='medicaldetailpasienkeluarga',
            name='nama_pasien',
        ),
        migrations.RemoveField(
            model_name='medicaldetailpasienkeluarga',
            name='tanggal_lahir',
        ),
        migrations.AddField(
            model_name='medicaldetailpasienkeluarga',
            name='keluarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_app.userkeluargainfo'),
        ),
    ]
