# Generated by Django 4.1.6 on 2023-05-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0020_remove_medicaldetailpasienkeluarga_hubungan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalclaimstatus',
            name='tidak_lengkap',
            field=models.CharField(blank=True, choices=[('Klaim tidak lengkap', 'Klaim Tidak Lengkap'), ('Klaim ditolak', 'Klaim Ditolak')], default='-', max_length=25, null=True),
        ),
    ]
