# Generated by Django 4.1.6 on 2023-06-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0021_alter_medicalclaimstatus_tidak_lengkap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetailinformation',
            name='jenis_pelayanan',
            field=models.CharField(choices=[('Rawat Jalan', 'Rawat Jalan'), ('Rawat Inap', 'Rawat Inap')], default=False, max_length=25),
        ),
    ]
