# Generated by Django 4.1.6 on 2023-06-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0022_alter_medicaldetailinformation_jenis_pelayanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetailinformation',
            name='jenis_pelayanan',
            field=models.CharField(default=False, max_length=25),
        ),
    ]
