# Generated by Django 4.1.6 on 2023-06-14 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrd_app', '0023_alter_medicaldetailinformation_jenis_pelayanan'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalRemain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(blank=True, choices=[('0', 'None'), ('K-0', 'K0'), ('K-1', 'K1'), ('K-2', 'K2'), ('K-3', 'K3'), ('T-1', 'T1'), ('T-2', 'T2'), ('TK', 'Tk')], default=False, max_length=25, null=True)),
                ('limit', models.PositiveBigIntegerField(blank=True, null=True)),
                ('used', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remain', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
