# Generated by Django 4.1.6 on 2023-07-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='masterTagVL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=128)),
                ('item_desc', models.CharField(max_length=128)),
                ('spec', models.CharField(max_length=128)),
                ('poc', models.FloatField(max_length=128)),
                ('poc_lower', models.FloatField(max_length=128)),
                ('poc_upper', models.FloatField(max_length=128)),
                ('vib', models.FloatField(max_length=128)),
                ('run_out', models.FloatField(max_length=128)),
                ('ro_low', models.FloatField(max_length=128)),
                ('ro_upper', models.FloatField(max_length=128)),
                ('tipe_pulley', models.CharField(max_length=128)),
                ('pulley_diameter', models.FloatField(max_length=128)),
                ('weigth_kg', models.PositiveBigIntegerField(max_length=128)),
                ('weight_n', models.PositiveBigIntegerField(max_length=128)),
                ('top_width', models.FloatField(max_length=128)),
                ('top_width_plus', models.FloatField(max_length=128)),
                ('top_width_minus', models.FloatField(max_length=128)),
                ('thickness', models.FloatField(max_length=128)),
                ('thickness_plus', models.FloatField(max_length=128)),
                ('thickness_minus', models.FloatField(max_length=128)),
                ('tipe_belt', models.BooleanField(default=False)),
            ],
        ),
    ]
