# Generated by Django 4.1.6 on 2023-07-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertagvl',
            name='weight_n',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='weigth_kg',
            field=models.PositiveBigIntegerField(),
        ),
    ]
