# Generated by Django 4.1.6 on 2023-07-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0002_alter_mastertagvl_weight_n_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastertagvl',
            old_name='weigth_kg',
            new_name='weight_kg',
        ),
    ]
