# Generated by Django 4.1.6 on 2023-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0003_rename_weigth_kg_mastertagvl_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertagvl',
            name='item_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='item_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='poc',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='poc_lower',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='poc_upper',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='pulley_diameter',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='ro_low',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='ro_upper',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='run_out',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='spec',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='thickness',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='thickness_minus',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='thickness_plus',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='tipe_pulley',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='top_width',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='top_width_minus',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='top_width_plus',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='vib',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='weight_kg',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastertagvl',
            name='weight_n',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
