# Generated by Django 4.1.6 on 2023-07-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0004_alter_mastertagvl_item_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertagvl',
            name='weight_n',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
