# Generated by Django 4.1.6 on 2023-07-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0005_alter_mastertagvl_weight_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertagvl',
            name='ro_low',
        ),
        migrations.RemoveField(
            model_name='mastertagvl',
            name='ro_upper',
        ),
    ]
