# Generated by Django 4.1.6 on 2023-07-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0006_remove_mastertagvl_ro_low_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POCVLRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_no', models.PositiveBigIntegerField(blank=True, null=True)),
                ('poc', models.FloatField(blank=True, max_length=128, null=True)),
                ('vib', models.FloatField(blank=True, max_length=128, null=True)),
                ('run_out', models.FloatField(blank=True, max_length=128, null=True)),
                ('ro_low', models.FloatField(blank=True, max_length=128, null=True)),
                ('ro_upper', models.FloatField(blank=True, max_length=128, null=True)),
                ('weight_kg', models.PositiveBigIntegerField(blank=True, null=True)),
                ('weight_n', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
