# Generated by Django 4.1.6 on 2023-07-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0008_pocvlrecord_created_at_pocvlrecord_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocvlrecord',
            name='ro_low',
        ),
        migrations.RemoveField(
            model_name='pocvlrecord',
            name='ro_upper',
        ),
        migrations.AddField(
            model_name='pocvlrecord',
            name='item_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pocvlrecord',
            name='item_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
