# Generated by Django 4.1.6 on 2023-07-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0009_remove_pocvlrecord_ro_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocvlrecord',
            name='center_distance',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pocvlrecord',
            name='poc_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pocvlrecord',
            name='run_out_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pocvlrecord',
            name='vib_status',
            field=models.BooleanField(default=False),
        ),
    ]
