# Generated by Django 4.1.6 on 2023-07-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0010_pocvlrecord_center_distance_pocvlrecord_poc_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocvlrecord',
            name='item_desc',
        ),
    ]
