# Generated by Django 4.1.6 on 2023-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0011_remove_pocvlrecord_item_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocvlrecord',
            name='so_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
