# Generated by Django 4.1.6 on 2023-07-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0012_alter_pocvlrecord_so_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocvlrecord',
            name='item_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
