# Generated by Django 4.1.6 on 2023-07-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0013_pocvlrecord_item_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocvlrecord',
            name='thickness',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pocvlrecord',
            name='top_width',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
    ]
