# Generated by Django 4.1.6 on 2023-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0014_pocvlrecord_thickness_pocvlrecord_top_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocvlrecord',
            name='thickness_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pocvlrecord',
            name='top_width_status',
            field=models.BooleanField(default=False),
        ),
    ]
