# Generated by Django 4.1.6 on 2023-07-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0015_pocvlrecord_thickness_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocvlrecord',
            name='shift',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
