# Generated by Django 4.1.6 on 2023-09-27 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_app', '0017_pocvlpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterTagLowModulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=128, null=True)),
                ('item_desc', models.CharField(blank=True, max_length=128, null=True)),
                ('spec', models.CharField(blank=True, max_length=128, null=True)),
                ('poc', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tension', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tension_plus', models.FloatField(blank=True, max_length=128, null=True)),
                ('tension_minus', models.FloatField(blank=True, max_length=128, null=True)),
                ('ride_out', models.FloatField(blank=True, max_length=128, null=True)),
                ('ride_out_plus', models.FloatField(blank=True, max_length=128, null=True)),
                ('ride_out_minus', models.FloatField(blank=True, max_length=128, null=True)),
                ('tipe_pulley', models.FloatField(blank=True, max_length=128, null=True)),
                ('pulley_diameter', models.FloatField(blank=True, max_length=128, null=True)),
                ('top_width', models.FloatField(blank=True, max_length=128, null=True)),
                ('top_width_plus', models.FloatField(blank=True, max_length=128, null=True)),
                ('top_width_minus', models.FloatField(blank=True, max_length=128, null=True)),
                ('thickness', models.FloatField(blank=True, max_length=128, null=True)),
                ('thickness_plus', models.FloatField(blank=True, max_length=128, null=True)),
                ('thickness_minus', models.FloatField(blank=True, max_length=128, null=True)),
                ('cpl100mm', models.FloatField(blank=True, max_length=128, null=True)),
                ('cpl1round', models.FloatField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='POCLowModulusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='POCLowModulusPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
