# Generated by Django 4.1.6 on 2023-09-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0018_mastertaglowmodulus_poclowmodulusrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertaglowmodulus',
            name='tipe_pulley',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
