# Generated by Django 4.1.6 on 2023-10-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0019_alter_mastertaglowmodulus_tipe_pulley'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertaglowmodulus',
            name='high_speed',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mastertaglowmodulus',
            name='low_speed',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mastertaglowmodulus',
            name='rpm',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
    ]
