# Generated by Django 4.1.6 on 2023-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0020_mastertaglowmodulus_high_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertaglowmodulus',
            name='is_doc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
