# Generated by Django 4.1.6 on 2023-10-16 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_app', '0022_pocvlrecord1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poclowmodulusrecord',
            old_name='poc',
            new_name='belt_no',
        ),
        migrations.RenameField(
            model_name='poclowmodulusrecord',
            old_name='ro_low',
            new_name='cpl100mm',
        ),
        migrations.RenameField(
            model_name='poclowmodulusrecord',
            old_name='ro_upper',
            new_name='cpl1round',
        ),
        migrations.RenameField(
            model_name='poclowmodulusrecord',
            old_name='run_out',
            new_name='doc',
        ),
        migrations.RenameField(
            model_name='poclowmodulusrecord',
            old_name='vib',
            new_name='ro',
        ),
        migrations.RemoveField(
            model_name='poclowmodulusrecord',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='poclowmodulusrecord',
            name='weight_n',
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='cpl100mm_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='cpl1round_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='item_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='item_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='ro_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='shift',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='tension',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='tension_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='thickness',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='thickness_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='top_width',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='top_width_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poclowmodulusrecord',
            name='so_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
