# Generated by Django 4.1.6 on 2023-10-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0023_rename_poc_poclowmodulusrecord_belt_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='build_no',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='poclowmodulusrecord',
            name='ddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='building date'),
        ),
    ]
