# Generated by Django 4.1.6 on 2023-02-24 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Request', 'Request'), ('Problem', 'Problem'), ('Peminjaman', 'Loan'), ('Other', 'Other')], default='Other', max_length=25)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('ticket_pic', models.ImageField(blank=True, upload_to='ticket_pics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hardware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='TicketApprovalIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_it', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_it', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_it', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketProgressIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('Waiting', 'In Approval It'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done')], default='Waiting', max_length=25)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Middle', 'Middle'), ('High', 'High')], default='Low', max_length=25)),
                ('review_description', models.TextField(blank=True, null=True)),
                ('ticket_approval_it', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.ticketapprovalit')),
                ('ticket_pic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketApprovalSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_supervisor', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_supervisor', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_supervisor', models.TextField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketApprovalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_manager', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket_approval_supervisor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.ticketapprovalsupervisor')),
            ],
        ),
        migrations.AddField(
            model_name='ticketapprovalit',
            name='ticket_approval_manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.ticketapprovalmanager'),
        ),
    ]
