# Generated by Django 4.1.6 on 2023-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('In Approval Supervisor', 'In Approval Supervisor'), ('In Approval Manager', 'In Approval Manager'), ('In Approval IT', 'In Approval It'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done')], default='In Approval Supervisor', max_length=25),
        ),
    ]
