# Generated by Django 4.1.6 on 2023-02-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_pic',
            field=models.ImageField(blank=True, upload_to='ticket_pics'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Request', 'In Request'), ('Problem', 'In Problem')], default='Request', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('In Approval Supervisor', 'In Approval Supervisor'), ('In Approval Manager', 'In Approval Manager'), ('Pending', 'In Approval It'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done')], default='In Approval Supervisor', max_length=25),
        ),
    ]
