# Generated by Django 4.1.6 on 2023-02-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0003_ticket_ticket_pic_ticket_type_alter_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_pic',
            new_name='ticket_photo',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_approve_it',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_approve_manager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_approve_supervisor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
