# Generated by Django 4.1.6 on 2023-02-27 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('it_app', '0003_ticketapprovalit_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketprogressit',
            name='ticket_pic',
        ),
        migrations.AddField(
            model_name='ticketapprovalit',
            name='it',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
