# Generated by Django 4.1.6 on 2023-02-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0004_remove_ticketprogressit_ticket_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_po', models.CharField(blank=True, max_length=64, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('kode_barang', models.CharField(blank=True, max_length=64, null=True)),
                ('Hardware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.hardware')),
            ],
        ),
    ]
