# Generated by Django 4.1.6 on 2023-02-22 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('it_app', '0004_rename_ticket_pic_ticket_ticket_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketApprovalIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_it', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_it', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_it', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_approve_it',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_approve_manager',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_approve_supervisor',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='TicketProgressIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'In Approval It'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done')], default='Waiting', max_length=25)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Middle', 'Middle'), ('High', 'High')], default='Low', max_length=25)),
                ('review_description', models.TextField()),
                ('ticket_approval_it', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.ticketapprovalit')),
                ('ticket_pic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketApprovalSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_supervisor', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_supervisor', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_supervisor', models.TextField()),
                ('supervisor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketApprovalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('reject_reason_manager', models.TextField()),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket_approval_supervisor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.ticketapprovalsupervisor')),
            ],
        ),
        migrations.AddField(
            model_name='ticketapprovalit',
            name='ticket_approval_manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.ticketapprovalmanager'),
        ),
    ]
