# Generated by Django 4.1.6 on 2023-02-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0005_hardwareinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Request', 'Request'), ('Problem', 'Problem'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticketprogressit',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done')], default='In Progress', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticketprogressit',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
