# Generated by Django 4.1.6 on 2023-02-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0005_ticketapprovalit_remove_ticket_is_approve_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Hardware',
            field=models.CharField(choices=[('AIO', 'Aio'), ('CCTV', 'Cctv'), ('Desktop', 'Desktop'), ('Keyence', 'Keyence'), ('Machine', 'Machine'), ('Notebook', 'Notebook'), ('Printer', 'Printer'), ('Server', 'Server'), ('Switch', 'Switch'), ('UPS', 'Ups'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Request', 'In Request'), ('Problem', 'In Problem'), ('Peminjaman', 'In Loan'), ('Other', 'In Other')], default='Other', max_length=25),
        ),
    ]
