# Generated by Django 4.1.6 on 2023-02-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0006_ticket_hardware_alter_ticket_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Hardware',
            new_name='hardware',
        ),
    ]
