# Generated by Django 4.1.6 on 2023-03-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0006_alter_ticket_type_alter_ticketprogressit_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_pic',
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='TicketAttachments/')),
                ('Ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.ticket')),
            ],
        ),
    ]
