# Generated by Django 4.1.6 on 2023-02-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0007_rename_hardware_ticket_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='hardware',
            field=models.CharField(blank=True, choices=[('AIO', 'Aio'), ('CCTV', 'Cctv'), ('Desktop', 'Desktop'), ('Keyence', 'Keyence'), ('Machine', 'Machine'), ('Notebook', 'Notebook'), ('Printer', 'Printer'), ('Server', 'Server'), ('Switch', 'Switch'), ('UPS', 'Ups'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Other', 'Other')], default='Other', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Request', 'Request'), ('Problem', 'Problem'), ('Peminjaman', 'Loan'), ('Other', 'Other')], default='Other', max_length=25),
        ),
    ]
