# Generated by Django 4.1.6 on 2023-03-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0008_hardware_created_at_hardware_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.CharField(choices=[('Request Application', 'Request Application'), ('Request Hardware', 'Request Hardware'), ('Request Emergency', 'Request Emergency'), ('Request Document & Data', 'Request Document Data'), ('Request Data', 'Request Data'), ('Problem', 'Problem'), ('Other', 'Other')], default='New', max_length=25),
        ),
        migrations.AddField(
            model_name='ticketprogressit',
            name='cost',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Request Application', 'Request Application'), ('Request Hardware', 'Request Hardware'), ('Request Emergency', 'Request Emergency'), ('Request Document & Data', 'Request Document Data'), ('Request Data', 'Request Data'), ('Problem', 'Problem'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AddField(
            model_name='hardware',
            name='Hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.hardwaretype'),
        ),
    ]
