# Generated by Django 4.1.6 on 2023-02-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0009_remove_ticket_hardware_remove_ticket_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_photo',
            new_name='ticket_pic',
        ),
    ]
