# Generated by Django 4.1.6 on 2023-03-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0009_hardwaretype_ticket_order_ticketprogressit_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.RenameField(
            model_name='hardware',
            old_name='Hardware',
            new_name='hardware',
        ),
        migrations.RenameField(
            model_name='hardwareinfo',
            old_name='Hardware',
            new_name='hardware',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.CharField(choices=[('New', 'New'), ('Renewal/Modification', 'Renewal'), ('Loan', 'Loan')], default='New', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Request Application', 'Request Application'), ('Request Hardware', 'Request Hardware'), ('Request Emergency', 'Request Emergency'), ('Request Document Data', 'Request Document Data'), ('Problem', 'Problem'), ('Other', 'Other')], default='Other', max_length=25),
        ),
    ]
