# Generated by Django 4.1.6 on 2023-03-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0010_software_rename_hardware_hardware_hardware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Renewal Or Modification', 'Renewal Or Modification'), ('Loan', 'Loan')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('Request Application', 'Request Application'), ('Request Hardware', 'Request Hardware'), ('Request Emergency', 'Request Emergency'), ('Request Document Data', 'Request Document Data'), ('Problem Hardware', 'Problem Hardware'), ('Problem Software', 'Problem Software'), ('Other', 'Other')], default='Other', max_length=25, null=True),
        ),
    ]
