# Generated by Django 4.1.6 on 2023-02-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0010_rename_ticket_photo_ticket_ticket_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketprogressit',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='ticketprogressit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ticket',
            name='hardware',
            field=models.CharField(blank=True, choices=[('AIO', 'Aio'), ('CCTV', 'Cctv'), ('Desktop', 'Desktop'), ('Keyence', 'Keyence'), ('Machine', 'Machine'), ('Notebook', 'Notebook'), ('Printer', 'Printer'), ('Server', 'Server'), ('Switch', 'Switch'), ('UPS', 'Ups'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Toner', 'Toner'), ('Other', 'Other')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
