# Generated by Django 4.1.6 on 2023-03-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0011_alter_ticket_order_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.CharField(choices=[('New', 'New'), ('Renewal Or Modification', 'Renewal Or Modification'), ('Lening', 'Lening')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Request Application', 'Request Application'), ('Request Hardware', 'Request Hardware'), ('Request Emergency', 'Request Emergency'), ('Request Document Data', 'Request Document Data'), ('Problem Hardware', 'Problem Hardware'), ('Problem Software', 'Problem Software')], max_length=25, null=True),
        ),
    ]
