# Generated by Django 4.1.6 on 2023-03-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0012_alter_ticket_order_alter_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.software'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.CharField(choices=[('New', 'New'), ('Renewal Or Modification', 'Renewal Or Modification'), ('Lening', 'Lening'), ('Problem', 'Problem')], max_length=25, null=True),
        ),
    ]
