# Generated by Django 4.1.6 on 2023-02-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0012_hardware_alter_ticket_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketapprovalsupervisor',
            name='reject_reason_supervisor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
