# Generated by Django 4.1.6 on 2023-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0014_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
