# Generated by Django 4.1.6 on 2023-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0015_ipaddress_ip_alter_ipaddress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprogressit',
            name='function_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketprogressit',
            name='function_start',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
