# Generated by Django 4.1.6 on 2023-05-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0016_ticketprogressit_function_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprogressit',
            name='function_end',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketprogressit',
            name='function_start',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
