# Generated by Django 4.1.6 on 2023-06-04 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('it_app', '0017_alter_ticketprogressit_function_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='quantity',
            new_name='quantity_whs',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='name',
        ),
        migrations.CreateModel(
            name='PCTypeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_type', models.CharField(max_length=126)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_app.hardwaretype')),
            ],
        ),
        migrations.CreateModel(
            name='ITComputerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=126)),
                ('os', models.CharField(choices=[('xp', 'Xp'), ('win7', 'Windows 7'), ('win8', 'Windows 8'), ('win10', 'Windows 10'), ('win11', 'Windows 11')], max_length=25, null=True)),
                ('windows_type', models.CharField(choices=[('oem', 'Oem'), ('olp', 'Olp')], max_length=25, null=True)),
                ('office_type', models.CharField(choices=[('office07', 'Office 2007'), ('office10', 'Office 2010'), ('office16', 'Office 2016')], max_length=25, null=True)),
                ('antivirus', models.CharField(choices=[('mc', 'Mcafee'), ('cr', 'Cyber Reason')], max_length=25, null=True)),
                ('is_internet', models.BooleanField(default=False)),
                ('computer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_app.ipaddress')),
                ('pc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_app.hardwaretype')),
            ],
        ),
    ]
