# Generated by Django 4.1.6 on 2023-06-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0018_rename_quantity_hardware_quantity_whs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='is_used',
        ),
    ]
