# Generated by Django 4.1.6 on 2023-06-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0019_remove_ipaddress_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='is_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
