# Generated by Django 4.1.6 on 2023-06-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0021_itcomputerlist_created_at_itcomputerlist_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itcomputerlist',
            name='is_office_2007',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itcomputerlist',
            name='is_office_2010',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itcomputerlist',
            name='is_office_2016',
            field=models.BooleanField(default=False),
        ),
    ]
