# Generated by Django 4.1.6 on 2023-06-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0022_itcomputerlist_is_office_2007_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itcomputerlist',
            name='office_type',
        ),
    ]
