# Generated by Django 4.1.6 on 2023-06-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0023_remove_itcomputerlist_office_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcomputerlist',
            name='antivirus',
            field=models.CharField(choices=[('mc', 'Mcafee'), ('cr', 'Cyber Reason')], max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='itcomputerlist',
            name='is_internet',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='itcomputerlist',
            name='is_office_2007',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='itcomputerlist',
            name='is_office_2010',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='itcomputerlist',
            name='is_office_2016',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='itcomputerlist',
            name='os',
            field=models.CharField(choices=[('xp', 'Xp'), ('win7', 'Windows 7'), ('win8', 'Windows 8'), ('win10', 'Windows 10'), ('win11', 'Windows 11')], max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='itcomputerlist',
            name='windows_type',
            field=models.CharField(choices=[('oem', 'Oem'), ('olp', 'Olp')], max_length=126, null=True),
        ),
    ]
