# Generated by Django 4.1.6 on 2023-06-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0024_alter_itcomputerlist_antivirus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcomputerlist',
            name='antivirus',
            field=models.CharField(choices=[('McAfee', 'Mcafee'), ('Cyber Reason', 'Cyber Reason')], max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='itcomputerlist',
            name='os',
            field=models.CharField(choices=[('Windows XP', 'Xp'), ('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11')], max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='itcomputerlist',
            name='windows_type',
            field=models.CharField(choices=[('OEM', 'Oem'), ('OLP', 'Olp')], max_length=126, null=True),
        ),
    ]
