# Generated by Django 4.1.6 on 2023-06-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0025_alter_itcomputerlist_antivirus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itcomputerlist',
            name='is_office_2003',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
