# Generated by Django 4.1.6 on 2023-06-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0026_itcomputerlist_is_office_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='itcomputerlist',
            name='is_genba',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
