# Generated by Django 4.1.6 on 2023-06-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0027_itcomputerlist_is_genba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcomputerlist',
            name='antivirus',
            field=models.CharField(blank=True, choices=[('McAfee', 'Mcafee'), ('Cyber Reason', 'Cyber Reason')], max_length=126, null=True),
        ),
    ]
