# Generated by Django 4.1.6 on 2023-06-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0028_alter_itcomputerlist_antivirus'),
    ]

    operations = [
        migrations.AddField(
            model_name='itcomputerlist',
            name='is_dhcp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='itcomputerlist',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.ipaddress'),
        ),
    ]
