# Generated by Django 4.1.6 on 2023-06-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0029_itcomputerlist_is_dhcp_alter_itcomputerlist_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='itcomputerlist',
            name='location',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
    ]
