# Generated by Django 4.1.6 on 2023-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0030_itcomputerlist_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=126)),
            ],
        ),
        migrations.RemoveField(
            model_name='itcomputerlist',
            name='location',
        ),
    ]
