# Generated by Django 4.1.6 on 2023-06-14 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0032_itcomputerlist_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcomputerlist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.listlocation'),
        ),
    ]
