# Generated by Django 4.1.6 on 2023-06-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0033_alter_itcomputerlist_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListLocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_detail', models.CharField(max_length=126)),
                ('location_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.listlocation')),
            ],
        ),
        migrations.AlterField(
            model_name='itcomputerlist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_app.listlocationdetail'),
        ),
    ]
