# Generated by Django 4.1.6 on 2023-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0034_listlocationdetail_alter_itcomputerlist_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcomputerlist',
            name='os',
            field=models.CharField(blank=True, choices=[('Windows XP', 'Xp'), ('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11')], max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='itcomputerlist',
            name='windows_type',
            field=models.CharField(blank=True, choices=[('OEM', 'Oem'), ('OLP', 'Olp')], max_length=126, null=True),
        ),
    ]
