# Generated by Django 4.1.6 on 2023-06-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0035_alter_itcomputerlist_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itcomputerlist',
            name='is_office_2019',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
