# Generated by Django 4.1.6 on 2023-07-14 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('it_app', '0037_report_ticketprogressit_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprogressit',
            name='pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
