# Generated by Django 4.1.6 on 2023-07-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0038_ticketprogressit_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_pending',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
