# Generated by Django 4.1.6 on 2023-08-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0040_itapprovallist_itreportd_itreportdattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itreporth',
            name='plan_actual_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itreporth',
            name='plan_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itreporth',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
