# Generated by Django 4.1.6 on 2023-08-01 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0041_alter_itreporth_plan_actual_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itreporth',
            name='project_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
