# Generated by Django 4.1.6 on 2023-08-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0042_itreporth_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itreportd',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_by_approvals', to='it_app.itapprovallist'),
        ),
        migrations.AlterField(
            model_name='itreportd',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pic_approvals', to='it_app.itapprovallist'),
        ),
    ]
