# Generated by Django 4.1.6 on 2023-08-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0043_alter_itreportd_confirmed_by_alter_itreportd_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itreportdattachment',
            old_name='medical',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='itreportd',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='itreportd',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
