# Generated by Django 4.1.6 on 2025-08-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMesin',
            fields=[
                ('id_mesin', models.FloatField(primary_key=True, serialize=False)),
                ('mesin', models.CharField(max_length=75)),
                ('id_line', models.CharField(blank=True, max_length=10, null=True)),
                ('nomer', models.CharField(blank=True, max_length=10, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tabel_mesin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenancePekerjaan',
            fields=[
                ('id_pekerjaan', models.FloatField(primary_key=True, serialize=False)),
                ('pekerjaan', models.CharField(max_length=50)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('gen_no', models.CharField(blank=True, max_length=1, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tabel_pekerjaan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SDBMSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hr.section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SDBMSubsection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hr.subsection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PengajuanMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pengajuan', models.CharField(max_length=50, unique=True, verbose_name='Nomor Pengajuan')),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pengajuan')),
                ('pengaju_employee_number', models.CharField(max_length=20, verbose_name='Employee Number Pengaju')),
                ('pengaju_name', models.CharField(max_length=100, verbose_name='Nama Pengaju')),
                ('pengaju_section', models.CharField(max_length=100, verbose_name='Section Pengaju')),
                ('pengaju_department', models.CharField(max_length=100, verbose_name='Department Pengaju')),
                ('line_section', models.CharField(max_length=100, verbose_name='Line/Section')),
                ('nama_mesin', models.CharField(max_length=75, verbose_name='Nama Mesin')),
                ('id_mesin', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Mesin')),
                ('section_tujuan', models.CharField(max_length=100, verbose_name='Section Tujuan')),
                ('jenis_pekerjaan', models.CharField(max_length=50, verbose_name='Jenis Pekerjaan')),
                ('id_pekerjaan', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Pekerjaan')),
                ('deskripsi_pekerjaan', models.TextField(verbose_name='Deskripsi Pekerjaan')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('prioritas', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Prioritas')),
                ('keterangan_tambahan', models.TextField(blank=True, null=True, verbose_name='Keterangan Tambahan')),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Disetujui Oleh')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Persetujuan')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan')),
                ('created_by', models.CharField(max_length=100, verbose_name='Dibuat Oleh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Update')),
            ],
            options={
                'verbose_name': 'Pengajuan Maintenance',
                'verbose_name_plural': 'Pengajuan Maintenance',
                'db_table': 'pengajuan_maintenance',
                'ordering': ['-created_at'],
            },
        ),
    ]
