# Generated by Django 4.1.6 on 2025-08-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wo_maintenance_app', '0001_initial'),
    ]

    operations = [
    ]
