# Generated by Django 4.1.6 on 2025-08-15 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wo_maintenance_app', '0002_add_section_change_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelApprovalLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('history_id', models.CharField(blank=True, max_length=15, null=True)),
                ('approver_user', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, help_text='1=approve, 2=reject', max_length=10, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tgl_approval', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Approval Log',
                'verbose_name_plural': 'Approval Log',
                'db_table': 'tabel_approval_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabelLine',
            fields=[
                ('id_line', models.FloatField(primary_key=True, serialize=False)),
                ('line', models.CharField(blank=True, max_length=35, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('user_insert', models.CharField(blank=True, max_length=30, null=True)),
                ('user_edit', models.CharField(blank=True, max_length=30, null=True)),
                ('tgl_insert', models.DateTimeField(blank=True, null=True)),
                ('tgl_edit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Line Production',
                'verbose_name_plural': 'Line Production',
                'db_table': 'tabel_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabelMesin',
            fields=[
                ('id_mesin', models.FloatField(primary_key=True, serialize=False)),
                ('mesin', models.CharField(blank=True, max_length=75, null=True)),
                ('id_line', models.CharField(blank=True, max_length=10, null=True)),
                ('nomer', models.CharField(blank=True, max_length=10, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('user_insert', models.CharField(blank=True, max_length=30, null=True)),
                ('user_edit', models.CharField(blank=True, max_length=30, null=True)),
                ('tgl_insert', models.DateTimeField(blank=True, null=True)),
                ('tgl_edit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mesin',
                'verbose_name_plural': 'Mesin',
                'db_table': 'tabel_mesin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabelMsection',
            fields=[
                ('id_section', models.FloatField(primary_key=True, serialize=False)),
                ('seksi', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('user_insert', models.CharField(blank=True, max_length=50, null=True)),
                ('user_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_insert', models.DateTimeField(blank=True, null=True)),
                ('tgl_edit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Section Maintenance',
                'verbose_name_plural': 'Section Maintenance',
                'db_table': 'tabel_msection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabelPekerjaan',
            fields=[
                ('id_pekerjaan', models.FloatField(primary_key=True, serialize=False)),
                ('pekerjaan', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('user_insert', models.CharField(blank=True, max_length=50, null=True)),
                ('user_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_insert', models.DateTimeField(blank=True, null=True)),
                ('tgl_edit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jenis Pekerjaan',
                'verbose_name_plural': 'Jenis Pekerjaan',
                'db_table': 'tabel_pekerjaan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabelPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(blank=True, max_length=15, null=True)),
                ('tgl_his', models.DateTimeField(blank=True, null=True)),
                ('jam_his', models.CharField(blank=True, max_length=12, null=True)),
                ('id_line', models.FloatField(blank=True, null=True)),
                ('id_mesin', models.FloatField(blank=True, null=True)),
                ('number_wo', models.CharField(blank=True, max_length=15, null=True)),
                ('deskripsi_perbaikan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, help_text='0=Pending, 1=Approved, 2=Rejected, 3=In Progress, 4=Completed', max_length=1, null=True)),
                ('user_insert', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_insert', models.DateTimeField(blank=True, null=True)),
                ('oleh', models.CharField(blank=True, max_length=500, null=True)),
                ('approve', models.CharField(blank=True, help_text='0=Not Approved, 1=Approved, 2=Rejected', max_length=10, null=True)),
                ('status_pekerjaan', models.CharField(blank=True, max_length=1, null=True)),
                ('id_pengajuan', models.IntegerField(blank=True, null=True)),
                ('id_section', models.FloatField(blank=True, null=True)),
                ('id_pekerjaan', models.FloatField(blank=True, null=True)),
                ('idpengajuan', models.FloatField(blank=True, null=True)),
                ('review_status', models.CharField(blank=True, default='0', help_text='0=Pending Review, 1=Reviewed Approved, 2=Reviewed Rejected', max_length=1, null=True)),
                ('reviewed_by', models.CharField(blank=True, help_text='Employee number of reviewer (007522)', max_length=50, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('final_section_id', models.FloatField(blank=True, help_text='Final section assigned by reviewer', null=True)),
            ],
            options={
                'verbose_name': 'Pengajuan Maintenance',
                'verbose_name_plural': 'Pengajuan Maintenance',
                'db_table': 'tabel_pengajuan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabelPengajuanAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('history_id', models.CharField(blank=True, max_length=15, null=True)),
                ('assigned_to_employee', models.CharField(blank=True, help_text='Employee number yang di-assign', max_length=50, null=True)),
                ('assigned_by_employee', models.CharField(blank=True, help_text='Employee number yang melakukan assign', max_length=50, null=True)),
                ('assignment_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assignment Pengajuan',
                'verbose_name_plural': 'Assignment Pengajuan',
                'db_table': 'tabel_pengajuan_assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabelReviewLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('history_id', models.CharField(blank=True, max_length=15, null=True)),
                ('reviewer_employee', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, help_text='approve, reject', max_length=10, null=True)),
                ('final_section_id', models.FloatField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Review Log',
                'verbose_name_plural': 'Review Log',
                'db_table': 'tabel_review_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pengajuan', models.IntegerField(default=0)),
                ('pending_approval', models.IntegerField(default=0)),
                ('pending_review', models.IntegerField(default=0)),
                ('approved', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('today_count', models.IntegerField(default=0)),
                ('this_week_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Work Order Statistics',
                'verbose_name_plural': 'Work Order Statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(default='007522', max_length=50, unique=True)),
                ('fullname', models.CharField(default='SITI FATIMAH', max_length=200)),
                ('is_active_reviewer', models.BooleanField(default=True)),
                ('review_authority', models.TextField(blank=True, help_text='Areas of review authority')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reviewer Profile',
                'verbose_name_plural': 'Reviewer Profiles',
            },
        ),
        migrations.DeleteModel(
            name='PengajuanMaintenance',
        ),
        migrations.DeleteModel(
            name='MaintenanceMesin',
        ),
        migrations.DeleteModel(
            name='MaintenancePekerjaan',
        ),
        migrations.DeleteModel(
            name='SDBMSection',
        ),
        migrations.DeleteModel(
            name='SDBMSubsection',
        ),
    ]
