# Generated by Django 4.1.6 on 2023-06-22 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePassSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_security', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GatePassInHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatepass_no', models.CharField(max_length=128)),
                ('nama', models.CharField(max_length=128)),
                ('nomor_identitas', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nomor_kendaraan', models.CharField(max_length=128)),
                ('jenis_kendaraan', models.CharField(choices=[('Mobil', 'Mobil'), ('Motor', 'Motor')], max_length=25, null=True)),
                ('status', models.CharField(default='In', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('Security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.gatepasssecurity')),
            ],
        ),
        migrations.CreateModel(
            name='GatePassInDetailTamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat_jalan', models.CharField(max_length=128)),
                ('nama_perusahaan', models.CharField(max_length=128)),
                ('nomor_identitas', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('gatepass_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.gatepassinheader')),
            ],
        ),
        migrations.CreateModel(
            name='GatePassInDetailKirimBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tujuan', models.CharField(choices=[('Meeting', 'Meeting'), ('Pickup Barang', 'Pickup')], max_length=25, null=True)),
                ('nama_perusahaan', models.CharField(max_length=128)),
                ('bertemu_dengan', models.CharField(max_length=128)),
                ('nomor_surat_jalan', models.CharField(max_length=128)),
                ('departemen', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('gatepass_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.gatepassinheader')),
            ],
        ),
    ]
