# Generated by Django 4.1.6 on 2023-10-24 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpPlanH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(blank=True, max_length=128, null=True)),
                ('duedate', models.DateTimeField(blank=True, null=True, verbose_name='Due date')),
                ('is_safety', models.BooleanField(blank=True, default=False, null=True)),
                ('is_productivity', models.BooleanField(blank=True, default=False, null=True)),
                ('is_quality', models.BooleanField(blank=True, default=False, null=True)),
                ('is_cost', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImpPlanD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(blank=True, max_length=128, null=True)),
                ('problem_desc', models.TextField(blank=True, null=True)),
                ('improvement_desc', models.TextField(blank=True, null=True)),
                ('target_desc', models.TextField(blank=True, null=True)),
                ('benefit_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('planh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ie_app.impplanh')),
            ],
        ),
    ]
