# Generated by Django 4.1.6 on 2023-10-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impplanh',
            name='is_cost',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='impplanh',
            name='is_productivity',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='impplanh',
            name='is_quality',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='impplanh',
            name='is_safety',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
