# Generated by Django 4.1.6 on 2023-10-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ie_app', '0002_alter_impplanh_is_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impplanh',
            name='is_cost',
        ),
        migrations.RemoveField(
            model_name='impplanh',
            name='is_productivity',
        ),
        migrations.RemoveField(
            model_name='impplanh',
            name='is_quality',
        ),
        migrations.RemoveField(
            model_name='impplanh',
            name='is_safety',
        ),
        migrations.AddField(
            model_name='impplanh',
            name='classification',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
