# Generated by Django 4.1.6 on 2023-10-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ie_app', '0003_remove_impplanh_is_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpPlanAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='PlanAttachment/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('planh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ie_app.impplanh')),
            ],
        ),
    ]
